### ISSUE TITLE
Some emoji, eg '😃' don't work, whereas others like '⏰' do

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#10016]
Moved from https://github.com/microsoft/terminal/issues/1606

Using app store preview build of Windows Terminal, with Win + x to send 😃 and then ⏰:

![image](https://user-images.githubusercontent.com/172594/60107029-149c0500-975e-11e9-81ab-a5475b746ac6.png)

@DHowett-MSFT mentioned it's likely not a Windows Terminal issue:

> Powershell has trouble with high unicode input ... and there's not much we can do to help that.

```

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I wonder if this is due to PS itself or PSReadLine...

Can you `Remove-Module PSReadline` and try it again?

**Comment by mikemaccana** [comment]
After `Remove-Module PSReadline`

![image](https://user-images.githubusercontent.com/172594/60305367-364ee500-9934-11e9-89ad-9cc599b723b6.png)

**Comment by vexx32** [comment]
Interesting. Input doesn't like it much, but output is OK.

I'd venture to say this is probably an issue both for PS itself in places and the PSReadLine module as well,

@daxian-dbw any thoughts on this?

**Comment by chuanjiao10** [comment]
😃 is 4 bytes utf16 char,powershell can not Rendering.This is a cancer of powershell.
Affects powershell5.1, 6.x, 7.x in win.Does not affect the powershell in Linux.
It from .net framework,i was report to ms 5years before.
if it can be fix , “microsoft terminal” will not be born


⏰ no problem。

test code:
```powershell
echo 'aaaa😃aaaa'
echo 'bbbb⏰bbbb'
```

**Comment by SteveL-MSFT** [comment]
Seems like there is an issue in both PS and PSRL.  We can keep this issue here for now.  Removing PSRL and on macOS, simply pasting `"😃` results in `�"😃�`.  Quite strange.

**Comment by chuanjiao10** [comment]
@SteveL-MSFT  I recommend marking it as 【won't fix】, and close this issue . The reason is: this problem has been fixed by win termal.

1 pwsh on linux does not have this problem.
2 powershell 6 and 6 on win has this problem, but there is no such problem in win termal. Powershell5.1 vs powershell 6.2.3
Test screenshot:

![image](https://user-images.githubusercontent.com/8968667/66113155-d20c8300-e5fe-11e9-8779-f02488f67ace.png)

Save the above test code to a.ps1 and add the bom header.

**Comment by SteveL-MSFT** [comment]
@chuanjiao10 that may be true on Windows, but on macOS there is still an issue although perhaps different from the original issue

**Comment by daxian-dbw** [comment]
In Windows Terminal, garbage characters may appear when deleting the emoji character.

**Comment by iSazonov** [comment]
@daxian-dbw Is any updates in PSRL with the issue?

**Comment by daxian-dbw** [comment]
@iSazonov Unfortunately, no news from the `PSReadLine` side. also, as mentioned in this issue, the same repros without `PSReadLine`.

**Comment by DHowett-MSFT** [comment]
PSReadline uses raw input and non-PSReadline uses `COOKED_READ` in the console host. One of these things can never be fixed :smile:

**Comment by iSazonov** [comment]
I'd prefer to get updated `COOKED_READ` in Core.

**Comment by DHowett-MSFT** [comment]
Cooked read is provided by conhost.exe, not Core, and we cannot change it without significantly impacting application compatibility all across Windows. Raw input with a readline-like library is the _correct_ thing to do.

**Comment by iSazonov** [comment]
> Raw input with a readline-like library is the correct thing to do.

I mean that this must be in Core so that we do not re-implement this in every application. Is there a tracking issue?
