### ISSUE TITLE
installing CentOS 8 rpm in Docker had links to SSL library which caused PowerShell to exit with New-PSSession

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#11147]
# Steps to reproduce

```powershell
in the centos8 docker image
install the rpm
start the installed shell
run new-pssession 
```

# Expected behavior

```none
error
```

# Actual behavior

```none
powershell exits
```

# Environment data

```none

```

**Comment by tomasruprich** [comment]
Just a quick note with more details and possible hotfix. 

The full error:
```
New-PSSession : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

Caused by non-existing libcrypto and libssl libraries:
```
# ls -l /opt/microsoft/powershell/6/libcrypto.so.1.0.0 /opt/microsoft/powershell/6/libssl.so.1.0.0 
lrwxrwxrwx. 1 root root 22 Jan 22 20:34 /opt/microsoft/powershell/6/libcrypto.so.1.0.0 -> /lib64/libcrypto.so.10
lrwxrwxrwx. 1 root root 19 Jan 22 20:34 /opt/microsoft/powershell/6/libssl.so.1.0.0 -> /lib64/libssl.so.10
# ls -l /lib64/libcrypto.so.10 /lib64/libssl.so.10
ls: cannot access '/lib64/libssl.so.10': No such file or directory
ls: cannot access '/lib64/libcrypto.so.10': No such file or directory
```

Solved by:
```
# sudo yum install -y epel-release
# sudo yum install -y compat-openssl10

# ls -l /lib64/libcrypto.so.10 
lrwxrwxrwx. 1 root root 19 May 13  2019 /lib64/libcrypto.so.10 -> libcrypto.so.1.0.2o
# ls -l /lib64/libssl.so.10 
lrwxrwxrwx. 1 root root 16 May 13  2019 /lib64/libssl.so.10 -> libssl.so.1.0.2o

```

**Comment by opoplawski** [comment]
With powershell 7.3.6 seeing similar.  Tried to fix with installing compat-openssl10 as well as:
```
sudo ln -s /usr/lib64/libcrypto.so.1.0.2o  /usr/lib64/libcrypto.so.1.0.0
```
But still getting an error:
```
> New-PSSession -ComputerName HOSTNAME -Authentication Negotiate -Credential USERNAME

PowerShell credential request
Enter your credentials.
Password for user USERNAME: ******************

New-PSSession: [HOSTNAME] Connecting to remote server HOSTNAME failed with the following error message : MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting Help topic.
```

**Comment by minerva26** [comment]
0x97F4Ba2A2cA8b60B3Dc074aDb7b0327b29A43B70
