### ISSUE TITLE
Appx - Import-Module: Operation is not supported on this platform. (0x80131539)

### ISSUE THREAD

**Issue by carlocardella** [PowerShell/PowerShell#13138]
## Steps to reproduce
Use Powershell 7.1 preview 4 or 5

```powershell
Import-Module Appx
```

## Expected behavior

```none
Successfully load the module
```

## Actual behavior

```none
ipmo Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The module can be imported properly in Powershell 7.0.2 or, in Preview 4/5 using `-UseWindowsPowerShell`.
I was able to load the module till 7.1 Preview 3

Is this an expected breaking change? Asking in case I need to update my scripts to use `-UseWindowsPowerShell`

**Comment by vexx32** [comment]
@SteveL-MSFT @joeyaiello this sounds like a consequence of the missing WinRT libraries. Somehow I doubt the Appx module maintainers will want to package the WinRT libs with their module / even if they do, it will mean anyone using newer versions of PS on older Windows versions will be unable to use the AppX module.

**Comment by carlocardella** [comment]
Here you go: 

```
[92mException             : [0m
    [92mType       : [0mSystem.PlatformNotSupportedException
    [92mTargetSite : [0m
        [92mName          : [0mGetExportedTypes
        [92mDeclaringType : [0mSystem.Reflection.RuntimeAssembly, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        [92mMemberType    : [0mMethod
        [92mModule        : [0mSystem.Private.CoreLib.dll
    [92mStackTrace : [0m
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    [92mMessage    : [0mOperation is not supported on this platform. (0x80131539)
    [92mSource     : [0mSystem.Private.CoreLib
    [92mHResult    : [0m-2146233031
[92mCategoryInfo          : [0mNotSpecified: (:) [Import-Module], PlatformNotSupportedException
[92mFullyQualifiedErrorId : [0mSystem.PlatformNotSupportedException,Microsoft.PowerShell.Commands.ImportModuleCommand
[92mInvocationInfo        : [0m
    [92mMyCommand        : [0mImport-Module
    [92mScriptLineNumber : [0m1
    [92mOffsetInLine     : [0m1
    [92mHistoryId        : [0m33
    [92mLine             : [0mipmo Appx
    [92mPositionMessage  : [0mAt line:1 char:1
                       + ipmo Appx
                       + ~~~~~~~~~
    [92mInvocationName   : [0mipmo
    [92mCommandOrigin    : [0mInternal
[92mScriptStackTrace      : [0mat <ScriptBlock>, <No file>: line 1
```

**Comment by joeyaiello** [comment]
Hmmmm, this I don't understand, as the compatible libraries should be available on the box. But it's WinRT, not NetFx, so we're probably not looking in the right place for them with our GAC logic. Or maybe the included WinRT libraries in 3.1 were forwarders all along? 

@adityapatwardhan can you and I talk about this one offline this week?

**Comment by daxian-dbw** [comment]
@joeyaiello PowerShell is likely still loading everything as it does in 7.0, but the CoreCLR cannot consume WinMDs anymore.
Quote from 
> #### Old behavior
> Consumption of WinMDs by CoreCLR was possible. This permitted activation and consumption of WinRT types.
>
> #### New behavior
> Direct consumption of WinMDs is no longer possible by CoreCLR.
>
> Examples of failures that may now occur:
> ...
> Activation of a WinRT class will result in the following:
>```
>Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539)
>```

**Comment by SeeminglyScience** [comment]
@joeyaiello It's throwing in [`Assembly::FindModuleByTypeRef`](https://github.com/dotnet/runtime/blob/cb1a7feaa43cdbd03b317db24fa30d86eae2a27c/src/coreclr/src/vm/assembly.cpp#L1039) when resolving an assembly reference with `WindowsRuntime` in it's assembly flags.  Loading the WinRT package won't change that unfortunately.  All binary modules that previously utilized WinRT will need to be recompiled to target the new package explicitly.  Don't think there's anything PowerShell can do about it.

**Comment by joeyaiello** [comment]
But as @SteveL-MSFT noted [here](https://github.com/PowerShell/PowerShell/issues/13042#issuecomment-653357546) (and @iSazonov below that), if the module author can put em back, than so can PS.

My question is whether we need both of those DLLs to get this WinMD support, or if we could ship something lighter that picks up the remaining right stuff off the Windows install. 

Also, I'd like to spend a little time understanding .NET's decision a little better. We may be reinventing the wheel here, or they may be a larger reason they pulled support in .NET 5 that we're missing. 

I'll try to do a little digging this week

**Comment by SeeminglyScience** [comment]
> But as @SteveL-MSFT noted [here](https://github.com/PowerShell/PowerShell/issues/13042#issuecomment-653357546) (and @iSazonov below that), if the module author can put em back, than so can PS.

That works because he's referencing the newly defined types from the package.  The AppX module directly references WinRT types.  This exception is at type load because of how the `AssemblyRef` is encoded.

> My question is whether we need both of those DLLs to get this WinMD support, or if we could ship something lighter that picks up the remaining right stuff off the Windows install.

I'd love to be wrong but I'm pretty sure there's nothing PowerShell can ship to make this work, other than a new version of the AppX module.

**Comment by SeeminglyScience** [comment]
The exception is too early in the code path for anything to be injected atm.  I don't know if this would work, but it might be worth talking to the dotnet team to see if the exception can be moved to after custom assembly resolve handlers are raised. *Maybe* if that was done the handler could point the resolution request to the new managed lib.

I'm guessing that would be flimsy at absolute best but maybe that sparks an idea for them.

**Comment by SeeminglyScience** [comment]
Nah that's a bust.  To test I manually removed the assembly ref flag for `WindowsRuntime` on the assembly in the GAC (ty dnSpy) and added an assembly resolve handler to point the ref to the new managed lib.  It actually works for the most part, but eventually I get a JIT exception because the new managed lib prefixes it's set accessor methods with `set_` instead of `put_`.

```raw
Exception             :
    Type       : System.MissingMethodException
    Message    : Method not found: 'Void Windows.Foundation.IAsyncOperationWithProgress`2.put_Completed(Windows.Foundation.AsyncOperationWithProgressCompletedHandler`2<!0,!1>)'.
    TargetSite :
        Name          : RunAppxOperation
        DeclaringType : Microsoft.Windows.Appx.PackageManager.Commands.AppxPackageManager
        MemberType    : Method
        Module        : Microsoft.Windows.Appx.PackageManager.Commands.dll
    StackTrace :
   at Microsoft.Windows.Appx.PackageManager.Commands.AppxPackageManager.RunAppxOperation()
   at Microsoft.Windows.Appx.PackageManager.Commands.AppxPackageManager.SetVolumeState(AppxVolume volume, Boolean setOnline)
   at Microsoft.Windows.Appx.PackageManager.Commands.MountAppxVolumeCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : Microsoft.Windows.Appx.PackageManager.Commands
    HResult    : -2146233069
CategoryInfo          : NotSpecified: (:) [Mount-AppxVolume], MissingMethodException
FullyQualifiedErrorId : System.MissingMethodException,Microsoft.Windows.Appx.PackageManager.Commands.MountAppxVolumeCommand
InvocationInfo        :
    MyCommand        : Mount-AppxVolume
    ScriptLineNumber : 1
    OffsetInLine     : 22
    HistoryId        : 34
    Line             : Get-AppPackageVolume|Mount-AppxVolume
    PositionMessage  : At line:1 char:22
                       + Get-AppPackageVolume|Mount-AppxVolume
                       +                      ~~~~~~~~~~~~~~~~
    InvocationName   : Mount-AppxVolume
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by SeeminglyScience** [comment]
I manually changed the method ref to `set_` in the strings heap and now everything appears to be working fine.  Maybe the team working on the managed lib could add `put_` accessors that point to the `set_` accessors for compat (hidden with `EditorBrowsableState.Never`).

**Comment by iSazonov** [comment]
It seems .Net team explicitly said that WinRT application should be recompiled in the case. So we need new version of the module.

**Comment by SeeminglyScience** [comment]
@iSazonov Yeah that's definitely their current stance.  It was pretty easy to coerce it into working though. I think it would be moderately easy for the dotnet team to enable an application to re-add support for these assemblies.  They would be able to keep actual support for winrt completely out of dotnet/runtime, but application like PowerShell could hook it back up potentially seemlessly.

Anyway that's mainly just to give @joeyaiello some ideas if he was still intending to discuss it with them.  If not then yeah just ship a new version I suppose.

**Comment by xmha97** [comment]
I have exactly the same problem. 😭

**Comment by salyounis** [comment]
> I manually changed the method ref to `set_` in the strings heap and now everything appears to be working fine. Maybe the team working on the managed lib could add fake `put_` accessors that point to the `set_` accessors for compat (hidden with `EditorBrowsableState.Never`).

can you place a download link of your package so can verify it too?

**Comment by SeeminglyScience** [comment]
@salyounis It was just for testing purposes, I would heavily advise against using an assembly whose metadata has been modified manually.

**Comment by TravisEz13** [comment]
We are still investigating this, but we are open to servicing this if this isn't fixed by 7.1 release.

**Comment by SteveL-MSFT** [comment]
Per .NET team, if we retarget the Windows release to `net50-windows`, that would pull in the WinRT assemblies and should work.  However, that new TFM isn't available until .NET 5 Preview 8.

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT are we 100% sure they mean it'll work without recompiling?  It fails at the runtime level, unless they plan on lighting up the assembly resolution logic again, this module will still need to be recompiled.

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience won't know until we try, the implication is that retargeting to the new TFM will pull in the necessary assemblies to make it work.  My suspicion is that a recompilation of Appx module is required, but that will then break running in Windows PowerShell.  The other option is to not mark it as Core compatible to have it go through the Windows PowerShell path.

Even now, you can just `import-module appx -usewindowspowershell` to get it working.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience won't know until we try, the implication is that retargeting to the new TFM will pull in the necessary assemblies to make it work.

This may already be understood so I apologize if I'm just reiterating facts y'all already know, but the point where this exception is thrown won't be affected by any additional assemblies.  It's hard coded to throw at type ref resolution well before any other code runs.  It's more or less the first stop in the code path.

Really I'm just trying to make sure y'all aren't banking on that working, if that's already understood then 👍 

> My suspicion is that a recompilation of Appx module is required, but that will then break running in Windows PowerShell. The other option is to not mark it as Core compatible to have it go through the Windows PowerShell path.

I did outline another potential path that would allow host processes like PowerShell to map these older assembly references to the new library.

1. Defer the exception in  [`Assembly::FindModuleByTypeRef`](https://github.com/dotnet/runtime/blob/cb1a7feaa43cdbd03b317db24fa30d86eae2a27c/src/coreclr/src/vm/assembly.cpp#L1039) until *after* assembly resolve events are raised.  If a registered handler finds the assembly then don't throw, if it does then throw the same exception
1. In the new WinRT package add `put_` methods that map to the new `set_` accessor methods for properties

If those are done then compat can be kept for these modules without compromising their goal of getting the code out of `dotnet/runtime`.

I just want to make sure all the options are being considered.  If y'all don't want to pursue that then 👍

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience spoke with .NET team and based on your idea, they agreed that to maintain compatibility, they would expose both set_ and put_ accessors for WinRT https://github.com/microsoft/CsWinRT/pull/402.  Thanks!

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT That's awesome! Thanks for talking to them.

Has there been any discussion with the runtime team regarding moving the assembly resolution exception? This is sort of an all or nothing scenario where if that part doesn't happen there won't be a need for the `put_` methods.

Just to spell it all out in case any of this isn't clear, let say we have a TypeRef encoded like this:

```il
.assembly extern windowsruntime Windows
{
    .ver 255:255:255:255
}

[Windows]Windows.Foundation.AsyncStatus
```

That sets the content type for the assembly as `WindowsRuntime`.

Assembly resolution at a high level looks like this:

1. Check if the content type is `WindowsRuntime` and throw `NotSupportedException`
1. Run any `AssemblyResolve` event handlers
1. Default resolve/load behavior

So ideally the PowerShell engine would be able to register an `AssemblyResolve` handler that looks something like this (psuedo code):

```csharp
Assembly Resolve(object sender, ResolveEventArgs args)
{
    if (args.Name.StartsWith("Windows") && args.Name.Contains("WindowsRuntime"))
    {
        return CsWinRTAssembly;
    }

    return null;
}
```

But because assembly resolution never makes it past the first step, that handler will never fire.  If the `NotSupportedException` could be moved until *after* assembly resolution doesn't find anything then compatibility could be kept.

Without that, these modules will still need to be recompiled and at that point they'll just use the `get_` accessors anyway.

**Comment by SteveL-MSFT** [comment]
Ok, after extensive discussions with .NET team and a change in their Windows.SDK assembly that handles WinRT calls to support both `put_` and `set_` for compatibility, the fix still requires Appx module to be retargeted for netstandard20.  Working with the Appx team to do this.  Since there is no change in PowerShell that can be done, closing this.

**Comment by doctordns** [comment]
> I'd love to be wrong but I'm pretty sure there's nothing PowerShell can ship to make this work, other than a new version of the AppX module.

In the short term, can we get the compatibility deny list updated? SInce this module can not work natively with PowerShell 7.1, let's just not load it (by default).

**Comment by iSazonov** [comment]
> In the short term, can we get the compatibility deny list updated? SInce this module can not work natively with PowerShell 7.1, let's just not load it (by default).

/cc @anmenaga

**Comment by juvtib** [comment]
What is the impact of 

```
WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; 
please note that all input and output of commands from this module will be deserialized objects. 
```

while working on a live system?

**Comment by iSazonov** [comment]
If a module is not supported in PowerShell the PowerShell creates a remote session to Windows PowerShell and run the module there. Limitation - you will receive reserialized objects in local session.

**Comment by juvtib** [comment]
So `Get-AppxPackage` will give accurate results and `Add-AppxPackage` will affect the live system? 
If this is true, what is the difference between working with de/serialized objects and live data?

**Comment by SeeminglyScience** [comment]
@juvtib When an object is serialized it loses methods, some properties may be typed differently or contain slightly different values, some may lose nested objects, and they may no longer work as arguments to strongly typed parameters.

Whether it effects your specific workflows is something you'll need to test to find out.

**Comment by doctordns** [comment]
Another side effect of the compatibility solution is that, at present, Display XML created by modules is not imported into the Parent PowerShell 7 session. So the output from commands such as Get-WindowsFeature produces sub-optimal output. You can, of course, always manually import the XML to get around this issue.

**Comment by fgimian** [comment]
I was too a bit surprised that a minor update (7.1) broke my scripts.  It's a shame because everything worked well in 7.0.3.

Based on the discussion above, are we likely to see the return of native Appx support in a future version of PowerShell or will we need to use the `-UseWindowsPowerShell` for all future PowerShell versions > 7.1?

Thanks heaps
Fotis

**Comment by doctordns** [comment]
given that Appx does NOT natively load in PowerShell 7, should that module be added to the deny list?

**Comment by Kein** [comment]
Same issue. Any ETA on this?

**Comment by asklar** [comment]
@SteveL-MSFT any updates on this? Still happening on 7.1.0

**Comment by ntpmhlk** [comment]
My workaround: 
Try default Windows Powershell(version 5). It works fine with `Get-appxpackage` command.

**Comment by JohannesWiesner** [comment]
> @SeeminglyScience won't know until we try, the implication is that retargeting to the new TFM will pull in the necessary assemblies to make it work. My suspicion is that a recompilation of Appx module is required, but that will then break running in Windows PowerShell. The other option is to not mark it as Core compatible to have it go through the Windows PowerShell path.
> 
> Even now, you can just `import-module appx -usewindowspowershell` to get it working.

I had the same issue, this comment solved it for me.

**Comment by jmroyb** [comment]
> > @SeeminglyScience won't know until we try, the implication is that retargeting to the new TFM will pull in the necessary assemblies to make it work. My suspicion is that a recompilation of Appx module is required, but that will then break running in Windows PowerShell. The other option is to not mark it as Core compatible to have it go through the Windows PowerShell path.
> > Even now, you can just `import-module appx -usewindowspowershell` to get it working.
> 
> I had the same issue, this comment solved it for me.

Me too! this comment solved it for me.

**Comment by juvtib** [comment]
``` powershell
Switch ($PSVersionTable.PSVersion.ToString())
{
  "7.1.0" {Import-Module -Name Appx -UseWindowsPowerShell; Break}
  "7.1.1" {Import-Module -Name Appx -UseWindowsPowerShell; Break}
}
```

**Comment by fgimian** [comment]
Is the `UseWindowsPowerShell` the correct solution moving forward?  I may be missing something but this was seemingly natively supported in PowerShell 7.0.x before.  Doesn't relying on Windows PowerShell go against the point that PowerShell 7+ is the future and supposed to replace Windows PowerShell?

Performing the import above adds an extra second or two to any script that uses Appx, when this wasn't the case or needed in 7.0.x.

Just trying to understand what the way forward here is 😄 

Thanks
Fotis

**Comment by SeeminglyScience** [comment]
> Just trying to understand what the way forward here is 😄

The module needs to be recompiled to reference the new CsWinRT library instead of referencing WinRT directly. The change itself **should** be pretty simple, but the module ships and Windows and probably isn't owned by PowerShell team so I wouldn't hold out for that.

**Comment by Starstrike** [comment]
This is still an issue in Powershell 7.1.3. I cannot run Get-AppxPackage and get told to run Import-Module Appx which also gives me an error.

![image](https://user-images.githubusercontent.com/1996734/111788558-9a4ad700-8896-11eb-8211-ce3878d75a07.png)

**Comment by assist726** [comment]
> This is still an issue in Powershell 7.1.3. I cannot run Get-AppxPackage and get told to run Import-Module Appx which also gives me an error.
> 
> ![image](https://user-images.githubusercontent.com/1996734/111788558-9a4ad700-8896-11eb-8211-ce3878d75a07.png)

Likewise same problem here

**Comment by keithnicholson** [comment]
I know this is closed, but I am having the same issue and now we cannot sideload app we have created in our company. Can there be a reference to another issue in process with another team if necessary.

**Comment by SeeminglyScience** [comment]
@joeyaiello @SteveL-MSFT Someone might want to reach out to the team that owns this module directly. This issue is getting some unusually high engagement for this repo.

**Comment by ds-steventondeur** [comment]
I got the same issue trying to install Ubutnu 20.04 without having to sign in into the windows store.
Using `Import-Module Appx -usewindowspowershell` worked for me but I had to search quite a bit before I ended up here and found the solution.

**Comment by koumaza** [comment]
We can use this.
No happen warning. But slow the same continually.

```pwsh
$Before_WarningPreference = $WarningPreference
$WarningPreference = 'SilentlyContinue'
Import-Module -Name Appx -UseWindowsPowerShell
$WarningPreference = $Before_WarningPreference
```

**Comment by SekiBetu** [comment]
`-usewindowspowershell` is not a solution, it only means we are using the old version of powershell, we need to stick to the problem and fix it.

**Comment by kyanha** [comment]
Can this issue be reopened until whatever's going on (and whatever happens with the AppX module in Windows 10) is fixed?  This breaks the Windows Store troubleshooting workflow.

**Comment by FuccDucc** [comment]
> Ok, after extensive discussions with .NET team and a change in their Windows.SDK assembly that handles WinRT calls to support both `put_` and `set_` for compatibility, the fix still requires Appx module to be retargeted for netstandard20. Working with the Appx team to do this. Since there is no change in PowerShell that can be done, closing this.

You wrote this in 2020

But now it is almost June 2021 and the issue persists..

entered `Get-AppxPackage appname | Remove-AppxPackage`

Error:
```
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
```

Went on to enter `Import-Module Appx` as it asks

Error:
```
Import-Module: Operation is not supported on this platform. (0x80131539)
```


It's only working on Powershell.exe from `C:\Windows\System32\WindowsPowerShell\v1.0` (Built into Windows 10), so for now until github powershell projects takes enough interest to end up getting it fixed, the github powershell is no proper replacement candidate for the windows built-in version of powershell.

Do you not strive for feature parity? You should take this as a serious issue.

**Comment by SteveL-MSFT** [comment]
I'll see if I can get more concrete plans from Appx team, but for now you can use:

```powershell
import-module appx -usewindowspowershell
```

**Comment by fgimian** [comment]
> ```powershell
> Import-Module -Name Appx -UseWindowsPowerShell
> ```

You can do this in one line actually:

```powershell
Import-Module -Name Appx -UseWindowsPowerShell -WarningAction SilentlyContinue
```

Like everyone else, I'm not really satsified with the current state of this broken functionality so I continue to use PowerShell 7.0.6.  Adding extra imports for this and Language for #14102 adds another 1+ second to the running of my scripts and/or profile.  All of this functionality worked perfectly before 7.1+ and I think that's the key here.

Both these issues have been closed here which just limits their visibility.  Depsite the issue being upstream, the functionality is broken in PowerShell itself.

**Comment by doctordns** [comment]
> My workaround :
> Try default Windows Powershell(version 5). It works fine with `Get-appxpackage` command.

Is this really the best advice we can get? Somehow abandoning PowerShell 7 for Windows PowerShell is rather sub-optimal to say the last. 

I understand that some product teams may be too busy, or lazy, to get their cmdlets fully working with PowerShell 7.  But this issue is nearly a year old and is still present in PowerShell 7.1.3, and the latest 7.2 preview and daily build versions.  

it does appear that you can force `Import-Module` to load the APPX module via compatibility. So can you extend the logic of the JSON file ban list to have a set of modules that Import-Module always loads using compatibility? So parhapx a powershell.config.json like this:

```powershell 
 
PS C:\Program Files\PowerShell\7> cat .\powershell.config.json
{
    "WindowsPowerShellCompatibilityModuleDenyList":  [
                                                         "PSScheduledJob",
                                                         "BestPractices",
                                                         "UpdateServices"
                                                     ],
    "Microsoft.PowerShell:ExecutionPolicy":  "RemoteSigned",
    "WindowsPowerShellForceWindowsCompatibility":  [
                                                         "Appx"
                                                     ]
}
```

**Comment by fgimian** [comment]
This is still broken on the very latest preview release;

```powershell
PowerShell 7.2.0-preview.8
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7-preview> Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
```

@SteveL-MSFT Would you kindly consider reopening this issue until it's fully resolved?  Is there any sort of ETA on this?

Huge thanks
Fotis

**Comment by iSazonov** [comment]
@fgimian The best thing you can do - report the issue by Windows Feedback tool to vote for fastest fixing the issue.

**Comment by aminya** [comment]
I also have the same issue
https://github.com/microsoft/winget-cli/issues/995#issuecomment-896572382

**Comment by roboticsMSM** [comment]
Same issue here.
When I type:
`Get-AppxPackage Microsoft.YourPhone -AllUsers | Remove-AppxPackage`
I expect Your Phone to be removed.
But I get this:
`Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.`

**Comment by fawdlstty** [comment]
same issue,
```
PowerShell 7.2.0-preview.8
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS F:\fawdlstty\Downloads\pwsh> get-appxpackage *store* | remove-Appxpackage
remove-Appxpackage: The 'remove-Appxpackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
PS F:\fawdlstty\Downloads\pwsh> Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
PS F:\fawdlstty\Downloads\pwsh>
```

```
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS F:\fawdlstty\Downloads\pwsh> get-appxpackage *store* | remove-Appxpackage
remove-Appxpackage: The 'remove-Appxpackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
PS F:\fawdlstty\Downloads\pwsh> Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
PS F:\fawdlstty\Downloads\pwsh>
```

**Comment by mshaikhcool** [comment]
@SteveL-MSFT This is really a deal breaker. can't use pwsh beyond `7.0.X`

 this is clearly a WinRT((aka COM version 2)) and .NET interop issue.  the right way to mitigate this on onwards .NET 5,  powershell team will have to make `ComWrappers` for these modules to work.

should this be filed in [CsWinRT ](https://github.com/microsoft/CsWinRT)repo ? 
i mean if appropriate, Can you please transfer the issue there so that they look at it? 
or _It's the powershell team that will have to make these modules `ComWrappers` compatible ?_

**Comment by oising** [comment]
Hah, and now I have finally arrived at this thread. I was trying to fix some broken crap in the latest win11 beta (windows defender ui missing) by using AppX to force resinstall the winsecui appx. I'm on 7.2p9. And I finally found my way here...

**Comment by asklar** [comment]
> @SteveL-MSFT This is really a deal breaker. can't use pwsh beyond `7.0.X`
> 
> this is clearly a WinRT((aka COM version 2)) and .NET interop issue. the right way to mitigate this on onwards .NET 5, powershell team will have to make `ComWrappers` for these modules to work.
> 
> should this be filed in [CsWinRT ](https://github.com/microsoft/CsWinRT)repo ?
> i mean if appropriate, Can you please transfer the issue there so that they look at it?
> or _It's the powershell team that will have to make these modules `ComWrappers` compatible ?_

cswinrt knows nothing of powershell or the appx PS module. CsWinrt can be used to produce a new version of the powershell appx module that can be used with .net 5+ though, so this should be on the appx team's plate, or powershell's.

**Comment by mshaikhcool** [comment]
> CsWinrt can be used to produce a new version of the powershell appx module that can be used with .net 5+ though.

that's the point. Why don't they do this ?  Does it take that much "investments" to make a powershell module `ComWrappers` compatible? At this point, from outside , It's very hard to even imagine that MSIX team even exists at microsoft. Just Look at them, it's been 3 years since release yet MSIX can't even install per machine, doesn't support SSH or WinRM, No Drivers support and [all the pains and sufferings](https://github.com/microsoft/winget-cli/issues/995#issuecomment-910898006) Winget team is constantly going through for choosing MSIX.  

MSIX, Basically can't even match with the old MSI format. what a disaster borrowed from UWP's APPX! sigh

**Comment by SpriggsySpriggs** [comment]
Still an issue in PowerShell v7.1.4

**Comment by riverar** [comment]
Agree, doesn't appear to be working on Windows 11 dev per release notes. https://blogs.windows.com/windows-insider/2021/09/15/announcing-windows-11-insider-preview-build-22458/#:~:text=appx%20commandlets

```
PS C:\> get-appxpackage
get-appxpackage: The 'get-appxpackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
PS C:\> Import-Module Appx
Import-Module: Unable to find the specified file.
PS C:\> $PSVersionTable                                                                                                 
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22458
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mshaikhcool** [comment]
**why on earth this issue is closed way before conforming that it actually works or not ?**
and why on earth a powershell module has to be tied to windows 11 ?

Yeah , the new microsoft tries to satisfy all but fails to pay attention to it's own platform. it's all about Lunatix and Azure.

**Comment by vexx32** [comment]
Powershell can't fix this issue. The issue is in the module itself, which is maintained by one of the Windows product teams.

If you want to have them prioritize it more urgently, you need to communicate that to the relevant team via the Windows Feedback tool.

**Comment by doctordns** [comment]
If this module can not be loaded at all in PowerShell 7, then shouldn't;'t it be on the module deny list JSON?

**Comment by pb5050** [comment]
> It would make sense to get PowerShell to do the work if the module owners won't or can't. **`I suggested extending the PowerShell JSON configuration file to implement a "WindowsPowerShellForceWindowsCompatibility" section to the JSON which tells PowerShell 7 to always load the modules named in that section using compatibility.`**



omg yes this would be so nice.

**Comment by vexx32** [comment]
Not sold on the naming there but yeah it would be nice to be able to configure that.

**Comment by doctordns** [comment]
> Not sold on the naming there but yeah it would be nice to be able to configure that.

I am defiantly not precious over naming and defer those who can do a better job! :-)

It would be, I feel, both fairly straightforward to implement and would give a much better user experience.

**Comment by Hashimlokasher** [comment]
Running following command fixed the issue for me.
`Import-Module Appx -usewindowspowershell`

**Comment by samus-a** [comment]
> Hello guys, I did a test on Windows 11 Insider build 22471 and I saw that the issue with AppX cmdlets has been fixed.
> 
> They have changed the `Appx.psd1` file from `CompatiblePSEditions = @("Desktop", "Core")` to `CompatiblePSEditions = @("Desktop")`, so that now the module gets always imported using WinCompat.
> 
> Wonder why releasing this simple workaround took so much 😃

The issue seems to have to do more with PowerShell 7 (7.2 in my case) than the version of Windows, since this only started to occured after upgrading to 7.2 (from 5) on both of my Windows 10 and 11 (official release) machinies.

**Comment by doctordns** [comment]
Here at least - I see that `Import-Module Appx` 'fails' in Windows 11 21H2. In my insiders build (22504). This now works. 

I am running PowerShell 7.2.0 on all hosts.

**Comment by LuanVSO** [comment]
hey i'm on windows 10.0.19044.1348 and when i try to import any module with `-usewindowspowershell` i get an error, here's the shell history:
[PowerShell use windowsps.txt](https://github.com/PowerShell/PowerShell/files/7585211/PowerShell.use.windowsps.txt)

ps: if i run powershell elevated it works

**Comment by alex19831362** [comment]
no reaction my power shell after import-module appx

**Comment by bogdan-patraucean** [comment]
> I get that the underlying issue is with the module and the module's owners.
> 
> At the same time if you use the `-UseWindowsPowerShell` property to import the module - the module works. I can't help thinking that If the error message had read "Please use Import-Module Appx -UseWindowsPowerShell" this would largely be a non-issue.
> 
> It would make sense to get PowerShell to do the work if the module owners won't or can't. I suggested extending the PowerShell JSON configuration file to implement a "WindowsPowerShellForceWindowsCompatibility" section to the JSON which tells PowerShell 7 to always load the modules named in that section using compatibility.
> 
> I believe there are things that PowerShell can do to protect me from these compatibility issues in a more intelligent way. By just force loading the appx module using compatibility would make this issue with appx go away.

Using `UseWindowsPowerShell` no longer works in Windows 11.

**Comment by MatiasAT** [comment]
Se puede solucionar ejecutando powershell_ise con permisos de administrador y en la base de la consola ejecutar los comandos.
![image](https://user-images.githubusercontent.com/51810798/160970389-ba665730-b78e-4396-9f1d-b7138838ae3c.png)

**Comment by asklar** [comment]
> Se puede solucionar ejecutando powershell_ise con permisos de administrador y en la base de la consola ejecutar los comandos. ![image](https://user-images.githubusercontent.com/51810798/160970389-ba665730-b78e-4396-9f1d-b7138838ae3c.png)

El ISE usa "Windows PowerShell", que es diferente (una version anterior) de PowerShell core (que es lo que de lo que habla este bug).

**Comment by bogdan-patraucean** [comment]
@carlocardella , this should be reopened as there are a lot of people complaining the error still occurs.

**Comment by soroshsabz** [comment]
Please reopen this issue

thanks

**Comment by SteveL-MSFT** [comment]
Long story short, I've been working with the AppX team on this issue.  They have been working on a fix which is not a small change.  The changes will not be backported to shipped versions of Windows and will show up in a future release of Windows.

**Comment by kyanha** [comment]
Then revert the change in pwsh that broke it. You broke it, you fix it. I have machines that bluescreen when I try to update them to Windows 11, and Microsoft's policies prevent me from activating fresh installs of 11 with the 10 Pro Retail keys that I bought for them. I am literally stuck because of MSFT and its employees. FIX THIS SO I CAN GET THE STORE WORKING AGAIN.

**Comment by daxian-dbw** [comment]
> Then revert the change in pwsh that broke it. You broke it, you fix it. 

Just to clarify it again, it was caused by an intentional breaking change in .NET Core, not PowerShell. See https://github.com/dotnet/docs/issues/18875 for details.

**Comment by ToxicSmurf** [comment]
> > Then revert the change in pwsh that broke it. You broke it, you fix it.
> 
> Just to clarify it again, it was caused by an intentional breaking change in .NET Core, not PowerShell. See [dotnet/docs#18875](https://github.com/dotnet/docs/issues/18875) for details.

Just to clarify again, why is this issue closed?

**Comment by Terafugia** [comment]
Well this is clear as mud. Closing an issue - that if you are unfortunately using Windows 10, can only be solved by upgrading to Windows 11 or becoming an insider?

**Comment by SeeminglyScience** [comment]
The issue is closed because the module is not part of this project. The feedback hub is the best way to reach the folks who own the AppX module.

**Comment by mikehearn** [comment]
Is there a piece of script that is:

a. Like the one by @juvtib above that detects the PowerShell version in use and then auto-fixes things?
b. Robust enough that it will NOT break in future releases of Windows or PowerShell?

To be clear, I - like everyone else here - do not care *at all* about whose fault inside Microsoft this problem is, or who is "supposed" to fix it. The amount of finger-pointing on this thread, the time taken to ship a fix and the fact that Win10 won't get it, is frankly absurd. Is it AppX, .NET team, WinRT, PowerShell team - who cares? Scripts that used to work now don't if someone upgrades to PS7.

**Comment by juvtib** [comment]
> a. Like the one by @juvtib above that detects the PowerShell version in use and then auto-fixes things?
> b. Robust enough that it will NOT break in future releases of Windows or PowerShell?

``` PowerShell
# some_file_name.ps1

$firstAffectedVersion = [System.Management.Automation.SemanticVersion]("7.1.0")

$lastAffectedVersion  = [System.Management.Automation.SemanticVersion]("999.0.0")

if (
  ($PSVersionTable.PSVersion -ge $firstAffectedVersion) -and 
  ($PSVersionTable.PSVersion -le $lastAffectedVersion )
)
{  Import-Module -Name Appx -UseWindowsPowerShell  }

```

* Use the [`[SemanticVersion]` :link:](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.semanticversion) class to make version comparisons. 
* Fill in `$lastAffectedVersion` when it is known. 
* [Dot source :link:](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scripts?view=powershell-7.2#script-scope-and-dot-sourcing) this code into affected scripts and sessions. 

The issue has not been fixed, so we don't know the true value for `$lastAffectedVersion` at this time. 

With dot sourcing, you can maintain your code in one place and use it in many scripts. 

``` PowerShell
# Dot Source Appx work-around.
. /path/to/some_file_name.ps1
```

I don't have Windows available to test. Please, test this code to make sure it is working. 

---

Or use Windows PowerShell 5.1: that is [`powershell.exe` :link:](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell#renamed-powershellexe-to-pwshexe)

## References 

* [Explanation of `-ge` and `-le`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators). 

* [Modules and Scope](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes#modules)

* [Automatically add code to every PowerShell session](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2). 


Regards,

**Comment by asklar** [comment]
CC @joshusto

**Comment by mikehearn** [comment]
Thank you @juvtib ! That is very helpful.

**Comment by rklec** [comment]
That script only seems to work in new PS versions (i.e. not Windows PowerShell), but PowerShell Core. In Windows PS I get the error that it cannot find `[System.Management.Automation.SemanticVersion]`.

And even in PowerShell Core I get some warning and it's horribly slow (so doing this at every initialisation is likely not really good):
```
PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Loading personal and system profiles took 6237ms.
```

**Comment by juvtib** [comment]
@rklec

Here is how I would solve the problem. 

If I am running `powershell.exe` (Windows PowerShell 5.1) then AppX works there and I don't need to make any checks or use the work-around. 

If I am running `pwsh.exe` (PowerShell 7) then I can use the work-around when needed. When you use it is up to you. You can put it in your profile, certain scripts, or run it manually. 

You can also modify my example to make additional checks. For example, you might use [WMI](https://docs.microsoft.com/powershell/scripting/samples/getting-wmi-objects--get-ciminstance-) to check what computer the script is running on or what operating system it has. Then, my example won't run on computers that don't use PowerShell 7. 

In PowerShell 7, your other options are to use the [PackageManager class](https://docs.microsoft.com/uwp/api/Windows.Management.Deployment.PackageManager) or [DISM](https://docs.microsoft.com/windows-hardware/manufacture/desktop/dism-app-package--appx-or-appxbundle--servicing-command-line-options). 

To answer your question, it looks like the SemanticVersion class is not available in PowerShell 5.1: 

![Semantic Version Class Not In SDK 5.1](https://user-images.githubusercontent.com/51273929/183414115-96a62c19-c7de-44ce-9859-fae500274f24.png)

Also, the format of `$PSVersionTable` changed between PowerShell 5.1 and PowerShell 7. Both of these issues would have to be addressed before my example would work across all PowerShell versions. Hopefully, some of these other options are helpful. 

Regards,

**Comment by mikehearn** [comment]
Thanks. In my case I'm distributing a script, so it has to "just work" for users regardless of what they've installed. So I'll need to figure out some script snippet that can work on both and figure out if it's PS7 or earlier.

**Comment by juvtib** [comment]
@mikehearn

Try running the version check in PowerShell 5.1 to see the exact error relating to the SemanticVersion class. 

Then wrap the version check in a [try and catch block](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-5.1). Catch the exception from the last step. And leave the catch block empty. We don't need to do anything on PowerShell 5.1 if the version check fails to run. 

In this way, if the SemanticVersion class is present then the work-around runs. 

And if the class is absent then you can assume you are using PowerShell 5.1 and no work-around is needed. 

If you want to share your work then you can try using a [gist](https://docs.github.com/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists). Feel free to copy my example there.

**Comment by mikehearn** [comment]
Thanks. Once we reach this task I'll share the code we come up with.

**Comment by sccook-intel** [comment]
> Using `UseWindowsPowerShell` no longer works in Windows 11.

I just successfully ran "import-module appx -usewindowspowershell" on Windows Server 2022 21H2 20348.1006, in case that helps anyone.

**Comment by igorskyflyer** [comment]
> > Using `UseWindowsPowerShell` no longer works in Windows 11.
> 
> I just successfully ran "import-module appx -usewindowspowershell" on Windows Server 2022 21H2 20348.1006, in case that helps anyone.

@sccook-intel, I started getting this error a few days ago but your workaround fixes it, thank you very much! 😁

**Comment by bogdan-patraucean** [comment]
@sccook-intel can you test this on Windows 11 22H2? I'm on the latest Insider Preview but still does not work.

**Comment by sccook-intel** [comment]
> @sccook-intel can you test this on Windows 11 22H2? I'm on the latest Insider Preview but still does not work.

Sorry; I'm on Windows 11 21H2, and don't have a newer version available to me. :-/

**Comment by FuccDucc** [comment]
I wanna copy over my comment from the other very similar issue #15428 where exactly the same root causes lead the maintainers to say "We dont care, not our problem, ok, closed":


> And you know, it doesn't matter if "it works on my machine" kind of crap. It's a MICROSOFT issue. If you're going to close a real issue, you should at least open another issue with the correct group.
>
> This kind of "closed because it's not a problem" is utterly rife with the new Microsoft. What happened? You guys used to be a great company.

@jgwinner (quote)

It's bureaucracy and that the teams within many large companies don't really work together/communicate properly or at all..
Even after more than a year, Microsoft didn't accomplish to let the OS/Appx/whatever other team, make a Microsoft product (that advertises itself as an improvement over the standard version) integrate properly. It's a failure of the chain or maybe the MS devs in github here are low level ones that don't have enough connections within the "real" company and can't break some barriers of team interoperability and cooperation. Of course, in the end, the result being produced is a symptom of lack of quality as a company, but the maintainers of this repo don't care enough and it's convenient to shove any such things with the thought "Not our problem / we dont get paid for this / there is invisible walls within Microsoft we cant break up, neither are we interested in looking at a solution for that"

_Originally posted by @FuccDucc in https://github.com/PowerShell/PowerShell/issues/15428#issuecomment-1347901516_

**Comment by jgwinner** [comment]
@FuccDucc Absolutely! 

> Of course, in the end, the result being produced is a symptom of lack of quality as a company, 

Yup, this is the problem. Still occasionally great, but just stupid sometimes. This is a failure of leadership at the top. 

I fear you're right about GitHub being low level employees who can't get anything done, but hopefully SOMEONE will bubble this up. It's why I try anyway.

Microsoft, you could be better. Please try.

**Comment by garretwilson** [comment]
I'm getting this error simply trying to run `Get-AppxPackage` in PowerShell 7.3.2. I installed PowerShell manually from `PowerShell-7.3.2-win-x64.msi`.

The status and workaround is unclear to me.

* Is someone going to fix this?
* Is there a workaround that does _not_ involve installing some third-party project off GitHub such as [`winget-installer`](https://github.com/asheroto/winget-installer)?

**Comment by juvtib** [comment]
The last response from Microsoft was: 

> Long story short, I've been working with the AppX team on this issue. They have been working on a fix which is not a small change. The changes will not be backported to shipped versions of Windows and will show up in a future release of Windows.


The standard work-around is to run the following command before using any cmdlets from the [AppX module](https://learn.microsoft.com/en-us/powershell/module/appx/): 

``` PowerShell
Import-Module -Name Appx -UseWindowsPowerShell

```

Alternatively, the AppX module is compatible with [PowerShell 5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell#powershell-executable-changes). You can launch PowerShell 5.1 by specifying its executable name: `powershell.exe`  Remember that PowerShell 6 and later use `pwsh.exe` as their executable name. 

That recent comment about WinGet is not relevant to this issue. 

Mike

**Comment by SkyNinja** [comment]
`Alternatively, the AppX module is compatible with [PowerShell 5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell#powershell-executable-changes). You can launch PowerShell 5.1 by specifying its executable name: powershell.exe Remember that PowerShell 6 and later use pwsh.exe as their executable name.`

Yeah, this isn't working for me. Every time I specify powershell.exe, even if I give the full path to it, it still gets redirected to pwsh.exe.

So good to know that MS's stance is "Oopsy woopsy, we bwoke it three years ago. Oh well, get a new operating system." With support like that, my new OS will be Ubuntu.

**Comment by travisterrell** [comment]
> Well this is clear as mud. Closing an issue - that if you are unfortunately using Windows 10, can only be solved by upgrading to Windows 11 or becoming an insider?

Super frustrating problem that still exists, and an even more frustrating Issue conclusion (Use the Feedback Hub.) 

It really sucks when we need to report a problem and the only mechanism Microsoft provides is via the Feedback Hub. It's impossible to get any feedback from Microsoft after doing so. It's similarly impossible to know whether others are experiencing the same issue or whether anybody has come up with a workaround. Or whether it is in fact an actual issue to begin with!

**Comment by bjmageto** [comment]
``` PowerShell
Get-AppXPackage: The 'Get-AppXPackage' command was found in the module 'Appx', but the module could not be loaded due to the following error: [Operation is not supported on this platform. (0x80131539)]
For more information, run 'Import-Module Appx'.
PS C:\Windows\System32> Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)
```

Still seeing the issue with PowerShell 7.3.5.  Solutions in thread to use the command

``` PowerShell
Import-Module -Name Appx -UseWindowsPowerShell
```

works but gives the following warning:

``` PowerShell
PS C:\Windows\System32> Import-Module -Name Appx -UseWindowsPowerShell
WARNING: Module appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```

**Comment by mklement0** [comment]
Let me attempt a **pragmatic summary**, as of late 2023:

The **problem**:

* The `AppX` module _was_ PowerShell Core-compatible, but only until v7.0.x.

* The move to .NET 5+ in PowerShell **7.1+** broke this, due to the [removal of built-in WinRT support from .NET](https://github.com/dotnet/docs/issues/18875).

* **In PowerShell 7.1+, as of this writing, the only way to use the module is via the [Windows PowerShell Compatibility](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) feature, with the _performance penalty_ and the _type-fidelity limitations_ that entails** (due to needing to use cross-process serialization via a hidden _Windows PowerShell_ child process).

* A proper fix - necessitating a recompiled `AppX` module, which _ships with Windows_ - is [_supposed to be_ coming, but _will not be back-ported_](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1180612320), so Windows 10 systems will definitely _not_ see it.


**Workarounds**:

* On **Windows 11** (presumably in [all currently deployed versions](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-938406311)):

  * Windows 11 ships with an updated `AppX` module that - as a stopgap - explicitly signals its _incompatibility_ with PowerShell Core, which means that - explicit or implicit import of the `AppX` module now _implies_ the `-UseWindowsPowerShell` switch, i.e. **_automatic_ use of the module via the Windows PowerShell Compatibility feature**, so **a workaround _may_ not be needed**:

    * You can verify that the presence of this updated module by running `Get-Module Appx -ListAvailable -All`: the `PSEdition` column should list `Desk` only (i.e. compatibility only with _Windows PowerShell_).

  * However, use of the Windows PowerShell Compatibility feature has two **side effects** that **you may want to suppress**, but doing so **requires an explicit `Import-Module` call**:
      *  It displays a _progress bar_ while the transient implicit-remoting module for communicating with the hidden Windows PowerShell child process is being created, when the module is first loaded, possibly _implicitly_ via the [module auto-loading](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Modules#module-auto-loading) feature. 
      *  When using an explicit `Import-Module` call, a _warning_ to alert the user to the limitations of Windows PowerShell Compatibility mode is displayed.
      * To suppress the progress bar you need an explicit `Import-Module` call, which in turn necessitates suppressing the warning:

        * `& { $ProgressPreference = 'Ignore'; Import-Module Appx 3>$null }`
  
  * If and when a truly PowerShell Core-compatible update arrives _via a future Windows update_, existing code (that doesn't explicitly use `-UseWindowsPowerShell`) will _automatically_ start using the new, natively compatible module.

* On **Windows 10**:

  *  **_Ad hoc_** workaround:
     *  Import the `AppX` module _explicitly_ and add `-UseWindowsPowerShell`.
     * To suppress the side effects discussed above:
       * `& { $ProgressPreference = 'Ignore'; Import-Module -UseWindowsPowerShell Appx 3>$null }`
 
  * **_Persistent_** workarounds, for a _given computer_ - if upgrading to Windows 11 isn't an option:

    *  Note: The following workarounds in effect cause _implicit_ use of the Windows PowerShell Compatibility features, as in Windows 11. Therefore, unless explicit importing is used as shown above, the _progress bar_ will show the first time a command from the `AppX` module is used in a given session, due to triggering auto-loading.
   
    * _Either_: Use `$PSDefaultParameterValues` to automatically apply `-UseWindowsPowerShell` dynamically via a script block; if you place the following in a [`$PROFILE` file](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Profiles), it will take effect for all future sessions, but note that profile loading can always be _bypassed_ with `-NoProfile`:

          $PSDefaultParameterValues['Import-Module:UseWindowsPowerShell'] = { 
            if ((Get-PSCallStack)[1].Position.Text -match '\bAppX\b') { $true } 
          } 

    * _Or_: Modify `"C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Appx\Appx.psd1"` to remove `'Core'` from the `CompatiblePSEditions` entry (which mimics the updated version of the module that ships with Windows 11).
      * This not only requires elevation, but requires taking ownership of the file first.
      * Obviously not a great solution, but I _think_ it would work, given that the module doesn't appear to be signed.
      * If subsequent OS updates don't yet include the fixed module, you'll have to do it again.

**Comment by jgwinner** [comment]
I just got a newish laptop and installed the new PS on it; while I did not run into the OP's issue as I have before with a new laptop (as noted above) I did get this:

```
WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```

Per this: https://learn.microsoft.com/en-us/answers/questions/295167/activedirectory-with-powershell-7-on-windows-serve looks like the built-in PS's prompt to load a new version of PS was, in fact, wrong?

lol. Such a mess.

I'm not going to worry with this because the new company is on AWS, not Azure, so I can let sleeping dogs sleep.

**Comment by CodedK** [comment]
Encountered a similar issue. Strangely, "...AppData\Local\Microsoft\WindowsApps" was not included in the system's PATH variable.

**Comment by soroshsabz** [comment]
@doctordns please reopen this issue and remove `external` tag

**Comment by robinwilson16** [comment]
Just hit this issue trying to install the new Teams client in Windows Server 2019 and found it did not recognise MSIX files at all then I had to install the latest PowerShell then I received the error listed here but the command from @juvtib worked and then I was able to run the install so the order of commands was:
```
Import-Module -Name Appx -UseWindowsPowerShell
Add-AppPackage -path ".\MSTeams-x64.msix"
```

However I then received an error saying I needed a Windows Developer Licence or a sideloading policy so I went to `Settings > Update & Security > For developers` and changed the option to allow sideloading.

After that I repeated the second command above and the appx package was installed.

So I got there in the end but why does everything have to be made so difficult 😅

It would be nice if supported operating systems could be updated, you know as if they were supported!

**Comment by juvtib** [comment]
@robinwilson16 Thanks for updating the procedure. For the record, I did not invent `Import-Module -Name Appx -UseWindowsPowerShell`--someone else did, and I believe PM Steve Lee endorsed it at some point. My contribution was collecting the steps that worked for me and putting them in one place: as you've done. :smiley:

**Comment by the-moog** [comment]
I tried all the above fixes, none work. Fairly sure I don't even want or need Appx in Win10?  If the canonical fix only works in win11 I am happy to get rid of Appx to get round these issues. Is that a possibility?   The forced adoption of this seems to be related to every issue I've had.

BTW: Recent Win10 Update completely screwed my machine with most things reporting similar errors, loads of inaccessible apps or apps reporting missing DLLs.  No start menu. One fix did a forced update to PS7 (which broke even more things). Broken WSL2. At one point most apps did not work.  Then those that were in the systray during the update. Tried dozens of so called PowerShell fixes, (most of which are like magic spells to me an I'm supposed to know a thing or two about computers..) Of those, most did more damage or nothing at all. The 'update' even removed the vendor supplied system restore partition! Thinking of just giving up and formatting HDD then installing Debian.  I only use Windows for some CAD software that does not run on Linux and Wine is getting useful.   Is all this an attempt to force the die hard 10 users to 11?  My machines have rarely got virus infections but when they have they did less damage. Now, I've fixed most issues (including WSL) but the start menu missing is annoying as I have to go seek the actual .exe to run anything.   Would removing appx (as this appears to be a win 11 thing) fix that?

**Comment by juvtib** [comment]
I'm sorry for your troubles. 

Based on the symptoms you describe, it sounds like you're having a more serious issue than a simple PowerShell error. And, I suggest looking for advice in a dedicated support forum or in a local repair shop. 

Note that AppX is just a file format (like .vhdx or .docx) which you can just ignore. There is nothing to gain by trying to remove support for AppX within Windows. 

Regards,

**Comment by sequencerr** [comment]
I have same problem on `7.4.1`, **but** not on `5.1.19041.4412`
Why the issue closed though?

**Comment by juvtib** [comment]
Windows PowerShell (v5) and PowerShell Core (v6+) are unrelated. 

Windows PowerShell was built into Windows and works correctly with the underlying AppX module. 

PowerShell Core is a cross-platform version of PowerShell which tracks .NET LTS. 

The AppX loading issue is specific to later versions of PowerShell Core. 

I can't remember the exact issue anymore. But, PowerShell Core inherited this issue when there was an underlying change in one of their dependencies. 

The project manager tried to contact that development team. And, there was some discussion. But, the issue was never resolved for Core. 

You'll have to load the full comment thread here to find a more specific reason why the issue was closed. In particular, the last comments from SteveL-MSFT should shed light on your question. 

If I was trying to automate AppX on Windows, I would try to use DISM or PowerShell v5 or some mobile device management software like Intune. I'm sure a sales rep or a "Microsoft-certified solution provider" would have more up-to-date information based on your needs. 

Regards,

**Comment by mklement0** [comment]
I know this thread is long, but, from what I can tell, [this comment](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1820195503) is still a (technically more detailed) summary of the state of affairs.

**Comment by Erquint** [comment]
`Visual Studio 2022 Developer PowerShell v17.11.5` bundled with `Microsoft.VisualStudio.2022.BuildTools 17.11.5` on `WinGet` is able to install AppX packages.  
Shame on M$ crutches…

**Comment by hawksj** [comment]
>     * _Or_: Modify `"C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Appx\Appx.psd1"` to remove `'Core'` from the `CompatiblePSEditions` entry (which mimics the updated version of the module that ships with Windows 11).
>       
>       * This not only requires elevation, but requires taking ownership of the file first.
>       * Obviously not a great solution, but I _think_ it would work, given that the module doesn't appear to be signed.
>       * If subsequent OS updates don't yet include the fixed module, you'll have to do it again.

This was the solution for me after loads of battling. It's taken me so long messing around with TrustedInstaller owned files just so I can play Forza Horizon 4 with Steam Link. I hate Microsoft, but thanks for the helpful responses in this thread.

**Comment by rugk** [comment]
Off-topic, but just FYI that game also has a quite good rating on ProtonDB for Linux gaming: https://www.protondb.com/app/1293830

<blockquote></blockquote>

**Comment by hawksj** [comment]
> Off-topic, but just FYI that game also has a quite good rating on ProtonDB for Linux gaming: https://www.protondb.com/app/1293830
> 
> <blockquote></blockquote>

Thanks, but not much help for this game in particular because Steam keys are not really sold any more and it can pretty much only be obtained on the Microsoft Store. Otherwise I absolutely would have bought it on Steam so I can continue playing when I move to Linux later this year. 

<blockquote></blockquote>
