### ISSUE TITLE
Update-Help returns error (error 404?)

### ISSUE THREAD

**Issue by shinayser** [PowerShell/PowerShell#16661]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I run the command:
```
PS C:\Users\shina> Update-Help -UICulture en-us
```

I get the following error:

```
Update-Help: Failed to update Help for the module(s) 'Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, PSReadline, Whea
WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

As you can see I am already forcing `en-us` local. And yes, I am invoking the command on a administrator terminal.

### Expected behavior

```console
I expected to be updated properly.
```

### Actual behavior

```console
Update-Help: Failed to update Help for the module(s) 'Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, PSReadline, Whea
WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```
```


### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by daxian-dbw** [comment]
@sdwheeler can you please take a look?

**Comment by sdwheeler** [comment]
Those modules all have known issues. The PSReadline problem is well documented in the blog.
https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by shinayser** [comment]
Thanks for your answer @sdwheeler. Taking a look at the article, I could figure out one small thing you said on it:
`Close all powershell.exe processes. Then rename the PSReadline module folder name to PSReadLine.`

What you mean about renaming the module folder? What folder? Where can I find that folders?
_Sorry asking but I am newbiee in powershell right now and I just started my studies recently._

**Comment by sdwheeler** [comment]
You can find the folder using:

```
Get-Module -ListAvailable PSReadline | Select-Object Path
```

**Comment by shinayser** [comment]
Interesting...the only PsReadline with lower case I got installed is from the oold "Windows Powershell" isntalation I got. I am using "Powershell" to update the help. Maybe thats a bug?

```
# That one is ok
C:\program files\windowsapps\microsoft.powershell_7.2.1.0_x64__8wekyb3d8bbwe\Modules\PSReadLine\PSReadLine.psd1

# That one is lower case
C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadline.psd1 
```

**Comment by adamobrennan** [comment]
@sdwheeler I have received a similar error when running the same command, and any variation on it I could find when googling this issue:

`Update-Help: Failed to update Help for the module(s) 'PSReadline' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.`

I tried the workaround you wrote in the URL above on a fresh install of 7.2.1 yesterday, but my folder had the correct capitalization: PSReadLine. So I tried it the incorrect way (how it is capitalized in the error, I noticed): PSReadline. Still no dice.

**Comment by adamobrennan** [comment]
I figured mine out - I added my Module folder to my PSModulePath in my system environment variables and it resolved my issue. When I got my error it was because it was looking at the Windows PowerShell 5.1 that came with my computer, where @sdwheeler is right and I had the documented issue going on as well. Hope any of this has been helpful, good luck @shinayser

**Comment by joegyamfi31** [comment]
@adamobrennan, could you please show how you added your Module folder to your PSModulePath in your system environment? I had similar issue. Thanks.

**Comment by daxian-dbw** [comment]
> Interesting... the only PsReadline with lower case I got installed is from the old "Windows Powershell" isntalation I got. I am using "Powershell 7.1.2" to update the help. Maybe thats a bug?

@shinayser The `PSReadLine` folder name for Windows PowerShell has been fixed in the latest Windows 10 (fix checked in in March 2021).

**Comment by Remzi1993** [comment]
> This issue has been marked as answered and has not had any activity for **1 day**. It has been closed for housekeeping purposes.

This issue is still very much relevant. I also got the same error. This shouldn't be happening on a production ready product.

**Comment by sdwheeler** [comment]
Adding a summary of answers for this issue is being before closing out comments.

The workaround for the **PSReadline** module is documented in the following blog post:

- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

This other thing to try is to unload the module, then reload it with the properly-cased name. Then update the help.

```powershell
Remove-Module PSReadline
Import-Module PSReadLine
Update-Help PSReadLine -Force
```

The error is expected for the following Windows modules. 

- ConfigDefenderPerformance
- Dism
- Get-NetView
- Kds
- NetQos
- PcsvDevice
- PKI
- StartLayout
- Whea
- WindowsSearch
- WindowsUpdate

The Windows modules are not maintained by the PowerShell team. To prevent the error, the module owners on the Windows team must fix the modules. For modules that ship in Windows, open a support case with Windows Support or send feedback via the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
