### ISSUE TITLE
Make it possible to host PowerShell in a custom assembly load context

### ISSUE THREAD

**Issue by albahari** [PowerShell/PowerShell#17492]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When Microsoft.PowerShell.SDK is run from a non-default ALC in .NET, Import-Module fails silently.

You can reproduce this with the following example (.NET 6 Console project). It works only if you comment out `#define USE_PLUGIN`.

```
#define USE_PLUGIN

using System.Collections.ObjectModel;
using System.Linq;
using System.Management.Automation;
using System.Reflection;
using System.Runtime.Loader;

#if USE_PLUGIN
    var pluginAlc = new PluginLoadContext(Assembly.GetExecutingAssembly().Location);
    var pluginAssem = pluginAlc.LoadFromAssemblyName(Assembly.GetExecutingAssembly().GetName());
    pluginAssem.GetType(nameof(Test)).GetMethod(nameof(Test.Run)).Invoke(null, null);
#else
    Test.Run();
#endif

Console.ReadLine();

public class Test
{
	public static void Run()
	{
		var ps = PowerShell.Create();
		ps.AddCommand("Import-Module").AddArgument(@"International");
		ps.AddScript("Get-WinHomeLocation");

		Collection<PSObject> result = ps.Invoke();

		if (ps.HadErrors)
			Console.WriteLine(ps.Streams.Error[0].ToString());
		else
			Console.WriteLine("Success!");

		foreach (PSObject element in result)
		{
			Console.WriteLine(element);
			foreach (var prop in element.Properties.Take(10))
				Console.WriteLine("    " + prop.Name + "=" + prop.Value);
		}
		Console.WriteLine();
	}
}

// Code from https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
class PluginLoadContext : AssemblyLoadContext
{
	private AssemblyDependencyResolver _resolver;

	public PluginLoadContext(string pluginPath)
	{
		_resolver = new AssemblyDependencyResolver(pluginPath);
	}

	protected override Assembly Load(AssemblyName assemblyName)
	{
		string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
		if (assemblyPath != null)
			return LoadFromAssemblyPath(assemblyPath);
		return null;
	}

	protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
	{
		string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
		if (libraryPath != null)
			return LoadUnmanagedDllFromPath(libraryPath);
		return IntPtr.Zero;
	}
}
```

### Expected behavior

```console
The program should print "Success" whether or not the USE_PLUGIN symbol is defined.
```

### Actual behavior

```console
When the USE_PLUGIN symbol is defined, the program displays the following error:

The term 'Get-WinHomeLocation' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

A possible reason for it misbehaving is that some of the same PowerShell assemblies end up being loaded into both the custom ALC and the default ALC. You can verify this with the following code:


Console.WriteLine("PowerShell assemblies loaded into plugin ALC:");
EnumeratePowerShellAssemblies(pluginAlc);

Console.WriteLine("PowerShell assemblies loaded into default ALC:");
EnumeratePowerShellAssemblies(AssemblyLoadContext.Default);

void EnumeratePowerShellAssemblies (AssemblyLoadContext alc)
{
    foreach (var a in alc.Assemblies)
        if (!a.IsDynamic && a.GetName().Name.StartsWith("Microsoft.PowerShell."))
            Console.WriteLine("    " + a.Location);
}
```
```


### Error details

```console
The term 'Get-WinHomeLocation' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
[PSVerion] 7.2.4
[OS] "Microsoft Windows 10.0.22000"
[WSManStackVersion] 3.0
[PSEdition] Core
[SerializationVersion] 1.1.0.1
[PSRemotingProtocolVersion] 2.3
[GitCommitId] 7.2.4
```

**Comment by daxian-dbw** [comment]
Currently, hosting PowerShell in a custom ALC is not supported, because it tightly coupled with the default assembly load context in many places, for example, 

- module loading uses `Assembly.LoadFrom` which implicitly loads an assembly into the default assembly load context.
- `Add-Type` also depends on `Assembly.LoadFrom`, as well as `AssemblyLoadContext.Default.LoadFromStream`.
- PowerShell class also depends on default load context.
- the helper resolver to load an assembly from GAC is registered with the default assembly load context.

Regarding the `International` module used in this repro, its assembly resides in GAC, so the helper resolver is used and load the assembly into the default load context. That's why you see some PowerShell assemblies get loaded in the default load context.

**Comment by albahari** [comment]
I appreciate your explanation, but would like something clarified. Are you saying that this is this an acceptable or recommended way for a library to load assemblies under .NET Core and .NET 5+? Or are you saying that fixing it would be too much work (or too potentially disruptive?)

As I understand, correct standard practice is to load assemblies into the same ALC as the requesting assembly:

```
var myAlc = AssemblyLoadContext.GetLoadContext (typeof (<typeInMyAssembly>).Assembly);
myAlc.LoadFromAssemblyName(...)
// or myAlc.LoadFromAssemblyPath(...) if you need to specify a path
```

This mimics the behavior of how assemblies **implicitly** load in  .NET Core and .NET 5+.

Hard-coding to the default ALC saves a line of code, but is reliable only if the requesting assembly is also in the default ALC. Otherwise it introduces the possibility of the assembly loading into both the default ALC and requesting ALC. And that almost never ends well.

**Comment by daxian-dbw** [comment]
> Are you saying that this is this an acceptable or recommended way for a library to load assemblies under .NET Core and .NET 5+? Or are you saying that fixing it would be too much work (or too potentially disruptive?)

It's not recommended to load PowerShell in a custom assembly load context as of today.
Fixing it is possible but would require non-trivial work. It's not just how loading assembly is handled in PowerShell, but also how types are resolved.

**Comment by sdcb** [comment]
The issue has not been resolved yet, please investigate further. The problem regarding hosting PowerShell in a custom assembly load context is still persisting and is a blocker for the project. Despite the lack of activity in the past 6 months, this matter requires attention and resolution.
