### ISSUE TITLE
Windows Defender has started to slowdown method calls in PowerShell dramatically

### ISSUE THREAD

**Issue by User1785604260** [PowerShell/PowerShell#19431]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following test.ps1 file with the latest Windows Defender signature version (e.g. 1.385.1608.0 at time of filing).
```powershell
for ($i = 0; $i -lt 40000; $i++) {
    $path = "C:\"
    $fileName = [System.IO.Path]::GetFileName($path)
    $fileExtension = [System.IO.Path]::GetExtension($path)
    
    $parent = $path.TrimEnd("\")
    $parent = [System.IO.Path]::GetDirectoryName($parent)
}
```

This script will take ~40ms with realtime protection turned off, vs ~8000ms with realtime protection turned on. The test script executes quickly with realtime protection turned on in PowerShell 5, however.

(**Note:** to address some pushback I received on reddit, yes, this is nonsense code doing nonsense work. The whole point is to demonstrate that just calling methods at all is taking a huge penalty all of the sudden.)

Furthermore, if I use my own infrastructure for timing code and execute the following:
```powershell
Invoke-Timed { [void]"".IndexOf("") } -Count 10000
```

I see 60 microseconds for each call with realtime protection turned on, vs 1 microsecond with realtime protection turned off. That same ```[void]"".IndexOf("")``` body can be placed into the for loop of the test.ps1 file to see the slowdown without my timing infrastructure.

It appears that the latest Windows Defender is significantly impacting method calls in PowerShell 7.

For a full repro, to make sure this isn't just something wrong with my install:
* Perform a fresh windows install of Windows 11 Pro 22H2 from Win11_22H2_English_x64v1.iso, with windows11.0-kb5023778-x64_204c2f5ab1eb71d80eb470b5af079dd8e56c20e7.msu already slipstreamed in
* Install windows using a local account (so none of my MS account settings are being brought in)
* Execute ```Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force -Verbose```
* Grab the latest winget: ms-windows-store://pdp/?productId=9NBLGGH4NNS1
* Install powershell 7.3.3: ```winget install -e Microsoft.PowerShell -a x64 --accept-package-agreements --accept-source-agreements```
* Observe that Windows Defender signature version is 1.321.69.0
* Run the test.ps1 file in PowerShell 5 and 7
* ```$stopwatch = [System.Diagnostics.Stopwatch]::StartNew(); powershell.exe -NoProfile -File "test.ps1"; Write-Host "Elapsed: $($stopwatch.ElapsedMilliseconds.ToString("N0"))ms"```
* ```$stopwatch = [System.Diagnostics.Stopwatch]::StartNew(); pwsh.exe -NoProfile -File "test.ps1"; Write-Host "Elapsed: $($stopwatch.ElapsedMilliseconds.ToString("N0"))ms"```
* Open Windows Defender and check for protection updates
* Observe that the signature version updates to e.g. 1.385.1608.0
* Wait for threat protection service to restart
* Re-execute the test.ps1 file in PowerShell 5 and 7
* Observe that the script remains fast in PowerShell 5, but dramatically slows down in 7
* Turn real-time protection off
* Observe that the fast script execution time is restored in 7

The issue appears to have started somewhere around signature version 1.385.1310.0, around March 27, 2023.

(**Edit:** reddit links removed. I couldn't get anyone to try my repro test.ps1 code out, so they were of limited value. ~~I'm still not sure if this issue is affecting anyone but me.~~ It's been confirmed below that I'm not the only one seeing this.)

While I understand this is probably an issue external to PowerShell 7, I thought the team should be aware and there's no Windows Defender GitHub repo for me to file an issue against.

(**Note:** Latest signature version where I'm still seeing this: 1.387.1114.0)

### Expected behavior

```console
Method calls like [void]"".IndexOf("") are fast, on the order of 1 microsecond, with Windows Defender realtime protection turned on.
```

### Actual behavior

```console
Method calls like [void]"".IndexOf("") are slow, on the order of 60 microseconds, with Windows Defender realtime protection turned on.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iRon7** [comment]
Noticed the same behavior as I was busy trying to improve the performance of my script which appeared suddenly a lot slower.
As [these performance tests](https://github.com/orgs/PowerShell/discussions/19322#discussioncomment-5396906) I created recently, appeared now a about 5 slower....

**Comment by iRon7** [comment]
@User1785604260,

> would you also be willing to measure the time on my specific repro case from above?

Yes, for your test:
With realtime protection on:  `~34000ms`
With realtime protection off:  `~200ms`

**Comment by User1785604260** [comment]
Perfect, thank you so much!

**Comment by SteveL-MSFT** [comment]
We'll pass this feedback to the Windows Defender team, but I would also suggest sending it via the Windows Feedback tool

**Comment by User1785604260** [comment]
Thanks for passing it along! Should I close this issue out now since the resolution is external and the team is aware?

**Comment by SteveL-MSFT** [comment]
@User1785604260  you can always close your own issues, but since a resolution label is set, our bot will close it automatically in a few days

**Comment by User1785604260** [comment]
Credit to another reddit user, they suggested disabling AMSI here: https://www.reddit.com/r/PowerShell/comments/12aqr8d/comment/jeuqmcp/

AMSI is not a thing I was aware of, and in my follow up comment I found that executing the following restored my script execution time, even with RTP turned on:
```
[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('s_amsiInitFailed','NonPublic,Static').SetValue($null,$true)
```

Note that RTP first needs to be turned off to execute that, and then back on again. Since it's, um, kinda malicious. 😊

I did file a Windows Feedback about this, but it just links back to this GitHub issue, so I wanted to keep it up-to-date.

**Comment by User1785604260** [comment]
Credit to [yet another reddit user](https://www.reddit.com/r/PowerShell/comments/12aqr8d/comment/jev7ruy/), presumably this is related: https://github.com/PowerShell/PowerShell/pull/16496

**Comment by User1785604260** [comment]
@SteveL-MSFT, given that an AMSI method-invocation scanning feature was specifically enabled in PowerShell 7.3, can you confirm whether the method call overhead I'm now seeing can be considered "normal" or not from the PowerShell team's perspective?

I'm wondering if this level of slowdown was always expected, and a switch just got flipped in Windows Defender, or if the slowdown I'm seeing now was not intended to eventually happen.

**Comment by iRon7** [comment]
@SteveL-MSFT,

> <kbd>Resolution-External</kbd>

Agree, but it clearly puts PowerShell (7.3.3) in a bad daylight compared to e.g. Windows PowerShell.

**Comment by daxian-dbw** [comment]
> This script will take ~40ms with realtime protection turned off, vs ~8000ms with **realtime protection** turned on.
> With **realtime protection off**: ~200ms, With **realtime protection on**: ~34000ms

I also run the script from https://github.com/PowerShell/PowerShell/issues/19431#issuecomment-1494528756 and see over 100x slowdown in execution time.

The AMSI method invocation logging was introduced in 7.3 and may play a role in this performance degradation.
Reassign to the Security WG for evaluation and suggestions for next step.

**Comment by adthom** [comment]
I had been chasing down a performance degredation over the last few weeks before I stumbled upon this issue.  After doing a bit of digging, my issues seemed to closely align to this scenario so I wanted to take a closer look.

I performed a test using a local release build of 7.3.3 and then of the same tag with the AmsiNativeMethods.AmsiNotifyOperation removed (just setting its hr to 0) from the AmsiUtils.WinReportContent method. I then tested both builds with the following:
```powershell
{
    $enc = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes(({
        $Count = 10000
        $str = 'A maasdlkfjoev 9r93 ldfjka.hdfhreu7\\ fkdjuenc'
        $SW = [Diagnostics.Stopwatch]::new()
        $SB = { [string]::new([char[]]$str.ToCharArray().ForEach({if([char]::IsLetterOrDigit($_)){return $_;}return ' '})) }
        $Total = 0l
        for ($i = 0; $i -lt $Count; $i++) {
            $SW.Restart()
            $null = $SB.InvokeReturnAsIs()
            $Total += $SW.ElapsedMilliseconds
        }
        $SW.Stop()
        $Total
        "# $($PSVersionTable['PSVersion']): { $($SB.ToString().Trim()) } took ${Total}ms for $Count iterations"
    }.ToString())))
    $Results = @("D:\Scratch\pwsh\7.3.3_no_amsinotify\pwsh.exe","D:\Scratch\pwsh\7.3.3\pwsh.exe").ForEach({ & $_ -NoProfile -NoLogo -EncodedCommand $enc })
    $Perf = ([long]$Results[2])/([double]([long]$Results[0]))
    Write-Host $Results[1]
    Write-Host $Results[3]
    Write-Host "Performance is $($Perf.ToString('F2')) times slower"
}.Invoke()
```
The version w/o AMSNofify ran 270x faster than the current release version:
```powershell
# 7.3.3: { [string]::new([char[]]$str.ToCharArray().ForEach({if([char]::IsLetterOrDigit($_)){return $_;}return ' '})) } took 77ms for 10000 iterations
# 7.3.3: { [string]::new([char[]]$str.ToCharArray().ForEach({if([char]::IsLetterOrDigit($_)){return $_;}return ' '})) } took 20851ms for 10000 iterations
Performance is 270.79 times slower
```
This seems to indicate that indeed, the bottleneck is on the Amsi provider side (my test case was using Windows Defender as well)

**Comment by vinaypamnani-msft** [comment]
+1 I've been fighting this for a month or so now, and I also notice pwsh.exe hammering the Windows Defender registry key since this issue started.

![image](https://user-images.githubusercontent.com/37223378/230660267-2b03deec-ebb6-43cf-a9a9-0aa9394e05bb.png)

I also have a test script that reproduces the issue. With RTP disabled, it takes 5 seconds, with RTP enabled, it takes 60 seconds.

```powershell
# Set the number of iterations to perform
$iterations = 1000

# Start a timer to measure the time taken to execute the loop
$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# Use a for loop to perform a series of calculations
for ($i = 1; $i -le $iterations; $i++) {
    # Perform some calculations here
    $result = 0
    for ($j = 1; $j -le $i; $j++) {
        $random = New-Object -TypeName System.Random
        $result += $random.Next(1,11)
    }

    # Update progress every 10 iterations
    if ($i % 10 -eq 0) {
        $percentComplete = ($i / $iterations) * 100
        Write-Progress -Activity "Calculating..." -PercentComplete $percentComplete -Status "Iteration $i of $iterations. Result = $result"
    }
}

# Stop the timer and calculate the elapsed time
$elapsedTime = $stopwatch.Elapsed
Write-Host "Elapsed time: $($elapsedTime.TotalSeconds) seconds"
```

**Comment by adthom** [comment]
I have been messing around with this further. The culprit is clearly the calls to AmsiNativeMethods.AmsiNotifyOperation. This call in and of itself is taking approximately ~40us to respond on each call, which is single-handedly causing the spike in latency. I have a version that I built which is caching the notifications sent to this method if they return the AMSI_RESULT_CLEAN result, as the [documentation indicates](https://learn.microsoft.com/en-us/windows/win32/api/amsi/ne-amsi-amsi_result#constants) that this return value should not change. 
I am caching with an LRU cache to only cache the last 500 calls (configurable) to limit the memory impact, though I am sure some logic between last recently used and most used would make more sense. This almost entirely mitigates the perf impact, and by placing the cache in the AmsiTools namespace, prevents manipulation of the cache in the same manner as the rest of the Amsi settings are protected.
As I am unsure as to where the LRU cache implementation would be best located, I do not have a PR ready to submit for this, as I do think this entire topic needs further discussion to ensure a caching mechanism does not significantly increase the exposure of this very important security measure.

**Comment by PaulHigin** [comment]
I am removing the WG-Security tag since this is not a security issue.  This is a (external) performance issue and should be marked accordingly.  The `AmsiNotifyOperation` API is supposed to be light weight and performant so I am not sure what has changed, but we can inquire internally.

**Comment by TravisEz13** [comment]
Defender has confirmed that this their issue and they are working on a fix.

**Comment by PaulHigin** [comment]
The Windows Defender team has identified the issue and has a fix for this performance degradation, and the fix should be pushed by the end of May.

**Comment by User1785604260** [comment]
@ParadoxGBB, if you're subscribed, I'll be posting here whenever I see it fixed, as long as no one else beats me to it.

I'm also keeping the original issue up-to-date every few days with the latest signature version that I'm still seeing as broken. (at the bottom)

**Comment by User1785604260** [comment]
This seems to be running "less worse" today, on signature version 1.389.2351.0. My repro code in the original issue is now about 10x slower, as opposed to 200x-ish slower with RTP turned on.

**Comment by ParadoxGBB** [comment]
@User1785604260, agreed, I went from of my use case scripts being about 8:30 before / 5:30 after / 2:30 RP off. Exclusions don't seem to help.

Hopefully, more work to come, wish this was reverted until it was fully vetted --- being able to disable the Asmi in PowerShell did not work for me when I tried a while ago.

**Comment by TravisEz13** [comment]
@User1785604260 
The update is supposed to release today.

To check if you have the update.

Run the powershell command `get-mpcomputerstatus`

```
PS > get-mpcomputerstatus
 
AMEngineVersion                  : 1.1.23050.3
AMProductVersion                 : 4.18.23050.3
````

The version should be 4.18.2305*, or newer, then the perf issue should be resolved.

**Comment by User1785604260** [comment]
I have the new version, but I'm still seeing the perf impact.

```
PS C:\> Get-MpComputerStatus | select am*

AMEngineVersion  : 1.1.23050.3
AMProductVersion : 4.18.23050.3
AMRunningMode    : Normal
AMServiceEnabled : True
AMServiceVersion : 4.18.23050.3
```

One of my scripts takes 0m:11s with RTP off (its original speed before all of this), but takes 1m:48s with RTP on. So nearly 10x slower. That is faster than it was when I first reported the issue, however, when it was around 50x slower.

**Comment by ParadoxGBB** [comment]
Got my update today, and it appears to have largely fixed the problem, for me at least. My production script (referenced before) went from 5 to 6 minutes execution to about 2:30. Turning off Real-time protection (which seems to make the MicrosoftSecurityApp.exe to go nuts on CPU and memory, BTW --- anyone have a link to know if this is known?) seems to be about the same.

**Comment by ColbyBouma** [comment]
23050 didn't help me either.

RTP on: 93 seconds  
RTP off: 5.5 seconds

Script: https://gitlab.com/GRC-Community/SpinRite-Logs/-/blob/main/6.1%20Alpha/Import-SpinRite61AlphaLog.ps1
```ps
$Logs = .\Import-SpinRite61AlphaLog.ps1 -LogPath . -Recurse -SkipSize 1mb -Verbose
```

```ps
PS C:\> Get-MpComputerStatus | Select-Object AM*

AMEngineVersion  : 1.1.23050.3
AMProductVersion : 4.18.23050.3
AMRunningMode    : Normal
AMServiceEnabled : True
AMServiceVersion : 4.18.23050.3
```

* PowerShell 7.3.4
* Windows 11 22H2 22621.1702

**Comment by iRon7** [comment]
Same for me, joining to object lists (as discussed [here](https://github.com/orgs/PowerShell/discussions/19322)) takes about 6 time longer in PowerShell version `7.3.4` than PowerShell version `7.2.10`.

**Comment by ColbyBouma** [comment]
> 23050 didn't help me either.

Actually, it did help once I rebooted.

RTP on: 6 seconds
RTP off: 3.8 seconds

I can live with that :)

**Comment by User1785604260** [comment]
I'm hoping we can get some official guidance on whether the remaining impact is considered acceptable and is the new normal for PowerShell 7.3+ going forward.
