### ISSUE TITLE
A - fundamentally unsupported - attempt to initialize a 2D (multidimensional) array with a literal results in a confusing error message

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20675]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Related:

* #20676

```powershell
[int[,]]  ((1,2), (2,3))
```

### Expected behavior

An error message indicating that initializing multidimensional arrays with (jagged) array literals isn't supported.

### Actual behavior

```console
InvalidArgument: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
```

This error message is confusing, and doesn't convey the root cause of the problem.

Curiously, (mistakenly) trying to assign a _1D_ array at least correctly reflects the multidimensionality of the target type, and the prefix changes from `InvalidArgument` to `OperationStopped`:

```
# -> "OperationStopped: Unable to cast object of type 'System.Int32[]' to type 'System.Int32[,]'."
[int[,]] @(1)
```

### Environment data

```powershell
PowerShell 7.4.0-rc.1
```

**Comment by u20221022** [comment]
Two dimensions (1024² = 1048576):
`[Int128[][]] $1048576 = ((1MB, 2MB),  (3MB, 4MB))`

`$1048576`
1048576
2097152
3145728
4194304

`$1048576[0]`
1048576
2097152

`$1048576[0][1]`
2097152

But three dimensions (1024³ = 1073741824):
`[Int128[][][]] $1073741824 = (((1MB, 2MB),  (3MB, 4MB)),   ((5MB, 6MB),  (7MB, 8MB)))`

`$1073741824`
Length         : 2
LongLength     : 2
Rank           : 1
SyncRoot       : {1048576, 2097152}
IsReadOnly     : False
IsFixedSize    : True
IsSynchronized : False
Count          : 2

Length         : 2
LongLength     : 2
Rank           : 1
SyncRoot       : {3145728, 4194304}
IsReadOnly     : False
IsFixedSize    : True
IsSynchronized : False
Count          : 2

Length         : 2
LongLength     : 2
Rank           : 1
SyncRoot       : {5242880, 6291456}
IsReadOnly     : False
IsFixedSize    : True
IsSynchronized : False
Count          : 2

Length         : 2
LongLength     : 2
Rank           : 1
SyncRoot       : {7340032, 8388608}
IsReadOnly     : False
IsFixedSize    : True
IsSynchronized : False
Count          : 2

`Write-Host $1073741824`
1048576 2097152 3145728 4194304 5242880 6291456 7340032 8388608

P.S.  «6291456» is a site bug, not PowerShell bug.

**Comment by 237dmitry** [comment]
@u20221022

Your array is single-dimensional, like `$arr[0][1]`, multi-dimensional is like `$arr[0,1]`:

```
$arr = [int32[,]]::new(1,3)
$arr[0,2] = 3
$arr[0,0] = 1
$arr[0,1] = 2

$arr[0,0]  # 1
```

**Comment by mklement0** [comment]
Indeed, @u20221022: What you're creating are _jagged_ arrays (arrays whose elements are arrays), not _multidimensional ones_ - but it is good to know that you can create _strongly typed_ jagged arrays.

While jagged arrays are far more common in PowerShell and are usually sufficient, this issue is about true multidimensional arrays.

---

As for your specific examples:

> `[Int128[][]] $1048576 = ((1MB, 2MB),  (3MB, 4MB))`

This creates a strongly typed two-element jagged array: each of its elements is also a 2-element array, so the total element count is `4`.

> `[Int128[][][]] $1073741824 = (((1MB, 2MB),  (3MB, 4MB)),   ((5MB, 6MB),  (7MB, 8MB)))`

This creates a more deeply nested jagged array that has `8` elements in total.
Due to the nesting of arrays, the standard display formatting is somewhat unfriendly, but you can get a better sense of the _structure_ with `Format-Custom -InputObject $1073741824` 

(`Write-Host` seemingly recursively enumerates jagged arrays and produces a flat display of all elements.)

`6291456` is what the `6MB` number literal evaluates to, and I'm unclear on why you think there's a bug and what the relevance of the commit you link to is.

**Comment by u20221022** [comment]
Now I understand that there is a difference between this two TYPES of arrays.  Sorry.  But I still do not understand what this difference is.  As to me, the jagged array is simply more convenient.

But you really do not see hyperlink «https: // github.com / PowerShell / PowerShell / commit / 6291456aa7aabb6f4285ee7eb3eaf3a5668c06d9» and pop-up window at ALL instances of number «6 291 456»?
![Всплывающее окно](https://github.com/PowerShell/PowerShell/assets/117870409/db308b68-52b6-4732-a861-9cab873ebda7)

**Comment by mklement0** [comment]
@u20221022: 

Ah, I see: Because you didn't use a code block around or inline code styling for `6291456` it turned into a hyperlink, because the number happened to match the ID (the first 7 (hex) digits of a commit-identifying SHA number) of a commit in this repo (you'll see the same number in the top-right corner of the linked page:

<img width="114" alt="image" src="https://github.com/PowerShell/PowerShell/assets/588825/a0e20e00-badf-4ca3-bfa6-3c72d68752fc"> and at the start of the linked page's last URL component)

I'd say it's a _feature_ of the site (I wasn't aware of it), though it is unusual that no sigil is required to use it (for linking to issues and PRs by their _issue number_, you need `#` as the sigil, e.g. #20675 to link to this issue). My _guess_ is that the assumption was that the likelihood of _accidentally_ using such numbers, especially since they often contain hex. digits (e.g., `7c2cb52`), which are usually prefixed with "0x" if meant to be mere _numbers_,  was low enough not require a sigil.

The short of it: to prevent such accidental links outside of fenced code blocks, enclose 7-digit hexadecimal numbers in `` `...` ``, which renders them as `6291456`, for instance, without a hyperlink.

**Comment by u20221022** [comment]
OK, thank you.

**Comment by mklement0** [comment]
@u20221022 

> As to me, the jagged array is simply more convenient.

Yes, _in PowerShell_ jagged arrays are easier to initialize and work with, and the performance advantage of true multidimensional arrays is usually not relevant.

> But I still do not understand what this difference is. 

In short:

A multidimensional array is a _single_ array of _fixed, preallocated size_ that can be accessed more efficiently than a jagged array. Elements must be accessed with a _single_ index expression that specifies an index for every dimension (e.g., `[1, 2]` to access an element in a 2D array).

A jagged array is composed of _multiple, nested_ arrays - an array whose elements happen to be arrays themselves.
Elements must be accessed with a _separate_ index expression, one for each array involved (e.g., `[1][2]` to access an element in a singly nested jagged array).

While slower than multidimensional arrays (because _multiple_ arrays must be accessed, in sequence), jagged arrays are more flexible:
* They allow each nested array to have a different element count (hence the name "jagged": you can think of a 2D-_like_ (singly nested) jagged array with elements of varying count as forming a table of values with a "jagged edge" rather than forming a perfect square of values as  a true 2D array would).
* They only occupy as much space as needed, whereas a multidimensional array invariably preallocates space for _all_ elements it can hold (e.g., a jagged array `[int[][]] $arrJagged = (1..100), $null` contains `102` elements in total (`2` for the outer array, and `100` for the nested array in its `[0]` element, none in the element `[1]`), whereas multidimensional array `$arr2D = [int[,]]::new(2, 100)` invariably contains `200` elements (the result of multiplying its dimensions, `2 * 100`).
* They allow swapping out nested arrays later, by assigning a different array to an element of the enclosing array (e.g., `$arrJagged[1] = 1..5`)

**Comment by u20221022** [comment]
Thank you again.
Until I plan to climb into such wilds. You can see it from my issues at this site.
I myself suspected about difference in speed and performance.  I remember the optimization tricks of Fortran on slow 360/370 series.
Thank you again and again.

**Comment by SeeminglyScience** [comment]
Looks like the conversion path `LanguagePrimitives.ConvertUnrelatedArrays` gets hit here which apepars not to check array rank. Definitely should at least fail more gracefully

**Comment by daxian-dbw** [comment]
Engine-WG reviewed this issue today and agreed that the error message should be improved. Marked this issue as a bug.

**Comment by u20221022** [comment]
So the bug was corrected or not?

**Comment by mklement0** [comment]
@u20221022: No, it wasn't fixed, only acknowledged as a bug. 

Bugs and feature requests can fall through the cracks, especially if they're deemed not to be important.

Labeling a bug as `Up-for-grabs` can help, as the community  can then contribute a PR.

The complexity of the fix usually decides whether that label is assigned or not, though it's possible that not assigning it was merely an oversight in this case.

**Comment by mklement0** [comment]
Anything that's already been labeled [Issue-Bug](https://github.com/PowerShell/PowerShell/issues?q=label%3AIssue-Bug) should _not_  be subject to auto-closure due to inactivity.
