### ISSUE TITLE
PS v7.4.1 breaks passing credentials to start-process

### ISSUE THREAD

**Issue by RaZz85** [PowerShell/PowerShell#21073]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Since updating to 7.4.1, it is no longer possible to pass credentials through to start-process. Running as admin makes no difference.

```
$credentials = get-credential
start-process -FilePath "C:\Windows\System32\mstsc.exe" -ArgumentList "/v:myrdpserver" -Credential $credential
```

### Expected behavior

```console
mstsc connects to myrdpserver with the provided credentials
```

### Actual behavior

```console
Start-Process: Access is denied.
```

### Error details

```console
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 5
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : OpenProcess
        DeclaringType : System.Diagnostics.ProcessManager, System.Diagnostics.Process, Version=8.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.Diagnostics.Process.dll
    Message         : Access is denied.
    Source          : System.Diagnostics.Process
    HResult         : -2147467259
    StackTrace      :
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.get_Handle()
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [Start-Process], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.StartProcessCommand
InvocationInfo        :
    MyCommand        : Start-Process
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : start-process -FilePath  "C:\Windows\System32\mstsc.exe" -ArgumentList "/v:myrdpserver" -Credent
ial $credential
    Statement        : start-process -FilePath  "C:\Windows\System32\mstsc.exe" -ArgumentList "/v:myrdpserver" -Credent
ial $credential
    PositionMessage  : At line:1 char:1
                       + start-process -FilePath  "C:\Windows\System32\mstsc.exe" -ArgumentLis …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : start-process
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jlapchuk** [comment]
Confirmed I'm experiencing the same issue after upgrading to v7.4.1. Attempting to Start-Process with -Credential fails with an 'Access is denied' error.

```
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

![image](https://github.com/PowerShell/PowerShell/assets/39131302/ca541344-2c4a-4c2a-8720-24a4eb3c1694)


```
NativeErrorCode : 5
ErrorCode       : -2147467259
TargetSite      : Microsoft.Win32.SafeHandles.SafeProcessHandle OpenProcess(Int32, Int32, Boolean)
Message         : Access is denied.
Data            : {}
InnerException  :
HelpLink        :
Source          : System.Diagnostics.Process
HResult         : -2147467259
StackTrace      :    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean
                  throwIfExited)
                     at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
                     at System.Diagnostics.Process.GetOrOpenProcessHandle()
                     at System.Diagnostics.Process.get_Handle()
                     at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
                     at System.Management.Automation.Cmdlet.DoBeginProcessing()
                     at System.Management.Automation.CommandProcessorBase.DoBegin()
```

**Comment by bartvermeersch** [comment]
@CodeCyclone could this be introduced by the code changes in [20749]( https://github.com/PowerShell/PowerShell/pull/20749 ) or  [20866](https://github.com/PowerShell/PowerShell/pull/20866) ? Thanks!

**Comment by aproposts** [comment]
Not sure if subscribing counts as a 'vote', so I'll add that I recently upgraded and am experiencing the same:

```powershell
$PSVersionTable
```

> ```
> Name                           Value
> ----                           -----
> PSVersion                      7.4.1
> PSEdition                      Core
> GitCommitId                    7.4.1
> OS                             Microsoft Windows 10.0.22631
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```

```powershell
$cred = Get-Credential someValidCredential
Start-Process -Credential $cred -FilePath notepad.exe
```

> ```
> Start-Process: Access is denied.
> ```

```powershell
Get-Error
```

> ```
> Exception             : 
>     Type            : System.ComponentModel.Win32Exception
>     NativeErrorCode : 5
>     ErrorCode       : -2147467259
>     TargetSite      : 
>         Name          : OpenProcess
>         DeclaringType : System.Diagnostics.ProcessManager, System.Diagnostics.Process, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>         MemberType    : Method
>         Module        : System.Diagnostics.Process.dll
>     Message         : Access is denied.
>     Source          : System.Diagnostics.Process
>     HResult         : -2147467259
>     StackTrace      : 
>    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
>    at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
>    at System.Diagnostics.Process.GetOrOpenProcessHandle()
>    at System.Diagnostics.Process.get_Handle()
>    at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
>    at System.Management.Automation.Cmdlet.DoBeginProcessing()
>    at System.Management.Automation.CommandProcessorBase.DoBegin()
> CategoryInfo          : NotSpecified: (:) [Start-Process], Win32Exception
> FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.StartProcessCommand
> InvocationInfo        : 
>     MyCommand        : Start-Process
>     ScriptLineNumber : 1
>     OffsetInLine     : 1
>     HistoryId        : 22
>     Line             : Start-Process -Credential $cred -FilePath notepad.exe
>     Statement        : Start-Process -Credential $cred -FilePath notepad.exe
>     PositionMessage  : At line:1 char:1
>                        + Start-Process -Credential $cred -FilePath notepad.exe
>                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     InvocationName   : Start-Process
>     CommandOrigin    : Internal
> ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
> ```

**Comment by Peter-76** [comment]
Same here - please fix!
In the meantime I go back to 7.0 :-(

**Comment by ChrisLynchHPE** [comment]
I just ran into this issue as well.  

```powershell

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I tried using PowerShell 7.5-Preview2 and had the same `Access Denied` error.  I removed 7.4.1, installed 7.4.0 and can successfully launch another process with `Start-Process -Credential $OtherAccount`.  Hope this gets resolved.

**Comment by Peter-76** [comment]
It is really disappointing that nothing is happening here  😞

**Comment by jlapchuk** [comment]
> It is really disappointing that nothing is happening here 😞

SAME! I was hoping this would be a quick and easy .2 fix, but I guess not? This is starting to impact our daily workloads as we have PS modules that require PowerShell 7 to function, but not being able to pass credentials to Start-Process is breaking all of that.

**Comment by TechNinja-PS** [comment]
> > It is really disappointing that nothing is happening here 😞
> 
> SAME! I was hoping this would be a quick and easy .2 fix, but I guess not? This is starting to impact our daily workloads as we have PS modules that require PowerShell 7 to function, but not being able to pass credentials to Start-Process is breaking all of that.

+1

**Comment by bartvermeersch** [comment]
It is impacting our workflows as well. After 2 months not even a bug tag is assigned on this issue.

**Comment by RaZz85** [comment]
Still no progress, this is halting our workflows quite badly.

**Comment by Peter-76** [comment]
What makes things worse for me is that with 7.4.1 this bug is fixed:
#20400 

So both versions, 7.4.0 and 7.4.1, have a bug that is impacting my daily work 😒
Maybe downgrading to 7.3.x is the best option for me.

**Comment by mmseng** [comment]
Same issue here. I used this functionality on a daily basis, so pretty impactful.

**Comment by jborean93** [comment]
I've opened https://github.com/PowerShell/PowerShell/pull/21393 which will treat the exception as a warning allowing people to still continue to use the `Process` object with methods like `WaitForExit()`. From what I've investigated this problem should only apply when

+ You are not running as admin, and
+ You are using a `-Credential` that is not your current user

If you are seeing this exception but do not fix into the above conditions please let me know and I'll have to do some further investigation to see what is happening.

A workaround is to use the [Process type](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-8.0) directly which should support pretty much all of the same scenarios that `Start-Process` does except for using `-Wait` to wait for that process and it's descendants. If you only need to wait for the direct process to end then that should work fine.
