### ISSUE TITLE
Allow to specify 2 spaces as column separator for tabular output

### ISSUE THREAD

**Issue by goyalyashpal** [PowerShell/PowerShell#21370]
### Summary of the new feature / enhancement

give an option in powershell to configure the space separation in different columns to at least 2 (or maybe hard-switch to it?)

'cz the current single space separated columns:

* make the table header super ambiguous, and ...
* impossible to parse with multi-word column headers
* i.e. unusable for structured operations with text-parser tools

though powershell provides mean to perform structured operations on data itself, 
but when creating user facing applications in powershell, ur application's user can't be forced to use powershell. 

and per may want/need to perform these operations on output itself using text based tools available at per's disposal.

example:

let's say the output is given below:
* now there is no way here to _correctly_ specify which among `"Length Name"` or `"Length", "Name"` should be valid.
* being able to specify to use 2 space as separator will _easily_ avoid all such issues 
* and provide unambiguous parsing with  `--separator=2+` 

```
Mode               Last Write Time         Length Name
----               ---------------         ------ ----
d-----        2025-06-28     25:37                file-1.txt
-a----        2024-09-11     17:87          25628 new-file-2.txt
-a----        2023-05-31     03:62           8534 lastfile.txt

```

**Comment by 237dmitry** [comment]
You can configure output view by yourself:

```powershell

Get-FormatData System.IO.FileInfo | Export-FormatData -Path Path/To/CustomFormat.FileInfo.ps1xml

# edit CustomFormat.FileInfo.ps1xml

Update-FormatData -PrependPath Path/To/CustomFormat.FileInfo.ps1xml
```

But I'am agree with your feature request for additional formatting parameters

**Comment by jhoneill** [comment]
TBH very, very little should ever parse the formatted output*, because the whole point of PowerShell was to objects that don't need to parsed - if stuff is going outside to some thing which needs to parse text the simple thing to do is push it through one of the convertTo commands and make it CSV, JSON or whatever. 

SOME tables definitely have an issue where - in the example - `length` is right aligned, and `name` is left aligned and only the dashes under the headings tell us we don't have a column named `length name` . There is other general tidying up needed in format table, despite changing the number formatting (which I think is a step forwards, and @237dmitry  doesn't) there is still a need to be able to say "format all numbers in this table in scientific notation / as currency/  with thousand separators"  etc . We can already set absolute width of columns and if I have headings Monday, Tuesday, Wednesday I would like to say "make all columns 10 wide instead of having different widths - which would also parsing. To be able to give a default number format, a default width, and a default gap to the next column would all be useful, and I would say should be done as one piece of work. I think, though, that the gaps are managed in a different part of the code.  

 
* This week I have been extracting things from the Windows event log which been put through format table, so there are some cases.

**Comment by goyalyashpal** [comment]
hi! thanks for thorough writeup.

> if stuff is going outside to some thing which needs to parse text the simple thing to do is push it through one of the convertTo commands and make it CSV, JSON or whatever.

i already addressed this above pt in description itself as:

> though powershell provides mean to perform structured operations on data itself,
but when creating user facing applications in powershell, ur application's user can't be forced to use powershell. 

that is, u (as in, the app creator) are not taking any responsibility to convert things. but ur users want to be able to, like they normally do.

having ability for these small formatting toggles in powershell output would increase the usability of outputs vastly without any recurring effort on user side, while still staying meaningful as normal CLI output as it is.

u'd agree too that csv, json etc other rigidly structured data aint very suitable alternate to clearly readable tables 😄 

> SOME tables definitely have an issue where - in the example - `length` is right aligned, and `name` is left aligned and only the dashes under the headings tell us we don't have a column named `length name`

yeah, i was thinking about that too. i thought the markdown table styled optional alignment indicators `:---  :---:  ---:` are an existing solution 😉

```console
> PS1-Command-with-alignment-markers | replace "  +" '|' | render-md-tables
``` 

🤣 😆 😂 

> To be able to give a default number format, a default width, and a default gap to the next column would all be useful, and I would say should be done as one piece of work. 

perfect 👌 

> I think, though, that the gaps are managed in a different part of the code.

ig that would make it long task if so...


> This week I have been extracting things from the Windows event log which been put through format table, so there are some cases.

can u share an anonymized sample? how did u parse it, i.e. using which format/tool?

**Comment by 237dmitry** [comment]
> which I think is a step forwards, and @237dmitry doesn't

In case you forgot, I promised I wouldn't talk about it.

As I understand  we are not talking about formatting the contents of the table columns, but about the distance between the columns.

**Comment by jhoneill** [comment]
> when creating user facing applications in powershell, ur application's user can't be forced to use powershell.


Well it becomes a kind of circular argument about if the application is a PowerShell one, to what degree is a user using PowerShell. 
A well implemented app outputs objects and gives PowerShell a definition of how those objects should be formatted. It is then up to the user of the app to say "But I want that data in a .XLSX " fine, use the import excel's Export-Excel command, "I want it in PDF", ok use  `out-printer "Microsoft Print to PDF"`  "I want it readable by some other random bit of code", the `export-csv` and `convertto-Json` commands are at your disposal.  
As an app developer you can say "But what about users who - even if shown they can run `myapp | export-csv`  blindly refuse to do anything that might be seen as _using_ PowerShell " (a) if they are important to you should you develop in something else and (b) You can provide "-OutputAs" switches and get your code to emit something which does not need prayer-based parsing. 
When the developer says "But I don't want to do that, and I want to cater for the screen scrapers and lovers of prayer-based parsing - therefore PowerShell should be changed". I think the idea might not gain traction :-) 

Not sure what your thinking I'd agree with, but stuff printed on the screen for a human to read and stuff output by one program for the use of another are distinct things - although a colossal amount of time and effort goes turning eyeball fodder back into data, and the reason for PowerShell's existence in the first place was to stop one set of programmers spending hours on converting data into text, and a second set spending hours on converting it back again.  There ARE cases where that is unavoidable, the screen scrape, or the case where one bit of code did 
```
$message = "Some stuff" + ($SomeData | format-Table | out-string -width 240) 
Write-EventLog  $message  -params
```
And the only way to get the information is Get-Eventlog | someParsing. 
I can't share the exact details  "Some stuff" was    Added, Deleted, Changed  records for a given type of data in a bulk load process &   the event log looks like 
```
Processed 256,128 FooBar records in 2 seconds. Delta is 
Added Changed 
-------  -------- 
 256    127
``` 
Note that we might not have all 3 columns, and some days some types have none. 
So I make an object with RecordType, RecordCount, Added, Changed, updated  and use a regex which matches the bits of the first line I want, any combination of heading, a line made up of - and spaces, and a line made up digits and spaces. 
It splits the the headings line and for each heading sets that property of the object to the corresponding value.  A pretty nasty regex, but I've written far worse :-) 

> In case you forgot, I promised I wouldn't talk about it.

Sorry to bring it up :-) FWIW I although I think what we have is better,  I don't think it is optimal.  The client I'm working for makes using pwsh 7 awkward so I have multiple places where I declare a whole bunch of columns and a number format and a width, and I wish FT had been given  -DefaultNumberFormat -DefaultDateFormat and -DefaultWidth  on day 1.

**Comment by goyalyashpal** [comment]
> It is then up to the user of the app to say "But I want that data in a .XLSX " fine, use the import excel's Export-Excel command, "I want it in PDF", ok use `out-printer "Microsoft Print to PDF"` "I want it readable by some other random bit of code", the `export-csv` and `convertto-Json` commands are at your disposal.

the thing is... lemme say again, 
* the user is not using powershell. 
* per is invoking ur application from whatever shell per pleases to, like `cmd`, `fish`, `bash`, `zsh`, whatever. 
* so those `export-csv`, `out-printer`, `convertto-json` etc powershell commandlets are _not available to the user_ in the first place.

> but stuff printed on the screen for a human to read and stuff output by one program for the use of another are distinct things

they generally are. but there are several things which in certain cases, fit both the categories: 
* aligned tables are easily parse able as `sql tables` (with whatever delimiting scheme: `markdown` tables, `asciidoc` tables, `csv`, `ssv`), 
* simple list data are easily parse able as `yaml`, ...

and these are more than enough i'd say. one single standard parsing command, and voilla, all the power of those `sql`, `yaml` querying tools is at ur fingertips just like that.

> therefore PowerShell should be changed

i mean, i get it; an application in current computing world likes to operate in its own surroundings. 
but regardless, the change is not like tip-to-toe kind of change. it's just adding one extra space in separation of columns. someone may even packet it as "increase padding among columns" where data is of relatively similar width across the column in all columns lol.

**Comment by goyalyashpal** [comment]
> object with RecordType, RecordCount, Added, Changed, updated and use a regex which matches the bits of the first line I want, any combination of heading, a line made up of - and spaces, and a line made up digits and spaces.
> It splits the the headings line and for each heading sets that property of the object to the corresponding value.

can you output it as `aligned` ? 
if yes, then u'd need one of those "pretty nasty regex", it becomes literally a 3 word readymade command.

if no, then maybe give it a second thought - find the max-width of column if possible and output according to that. the benefits are immense if u do lots of parsing of output.

**Comment by jhoneill** [comment]
> > It is then up to the user of the app to say "But I want that data in a .XLSX " fine, use the import excel's Export-Excel command, "I want it in PDF", ok use `out-printer "Microsoft Print to PDF"` "I want it readable by some other random bit of code", the `export-csv` and `convertto-Json` commands are at your disposal.
> 
> the thing is... lemme say again,
> 
> * the user is _not_ using powershell.
> * per is invoking ur application from whatever shell per pleases to, like `cmd`, `fish`, `bash`, `zsh`, whatever.
> * so those `Export-Csv`, `Out-Printer`, `ConvertTo-Json` etc powershell commandlets are _not available to the user_ in the first place.

At risk of a dialog of the deaf here.
You've implemented something in PowerShell.  The user is either (a) sitting in power shell (b) Invokes PowerShell and runs your app, then exits, or (c) runs `pwsh yourapp -parameters`  from their existing shell. 
Now if they want to process the output of your they might wail they want to do   `pwsh yourapp -parameters | prayer-based-parsing`,  to which the answer is they run    `pwsh "yourapp -parameters | convertto-Csv   " | simpler-parsing` they will save a lot of time and effort.    If even that is too much for them - and you consider them to be worth helping you can go down the route that IIRC terraform uses and have a command line switch to emit something made for parsing if they then complain the parsing is CSV is too easy, they can hardly complain that the table layout is too hard.    Some people will complain simply because you've implemented the thing in PowerShell :-) 

> >  stuff printed on the screen for a human to read and stuff output by one program for the use of another are distinct things
> 
> they generally are. but there are several things which in certain cases, fit both the categories...

I've been pasting into excel and doing "text to columns" for 35 years :-)  But it's like doing OCR on a fax, instead of sending an email.  I wrote my first screen scraper excel Macro in about 1991, still pull text from websites apart, because sometimes there isn't a better way. But as soon as someone formats a date, or decides that numbers are easier to read with thousand separators or uses the same code in two countries, things get problematic.  All that experience means I can parse anything I need to, and I know what a dreadful waste of time and effort it is,  and for the last 16 or 17 years I've been saying "hey, with PowerShell we can get on with other stuff instead of smelting stuff out of printout"  
  
> > therefore PowerShell should be changed
> 
> i mean, i get it; an application in current computing world likes to operate in its own surroundings. but regardless, the change is not like tip-to-toe kind of change. it's just adding one extra space in separation of columns. someone may even packet it as "increase padding among columns" where data is of relatively similar width across the column in all columns lol.

I'm looking it from a "how is time going get assigned to doing this" perspective. Can and should some of the stuff in format-table be improved? Yes! Just look at what you need to write to format and arbitrary lump of data with equal sized columns (that's so painful no one has suggested "hey, why not just have wider columns" ) Want to force a number format on every column, same tedious process. Fix those and allow control of the gap between autosized columns. BUT don't try to get the PowerShell folks to do something because it will make parsing better, no-one is going to see that as a reason to lift a finger.

 




> > object with RecordType, RecordCount, Added, Changed, updated and use a regex which matches the bits of the first line I want, any combination of heading, a line made up of - and spaces, and a line made up digits and spaces.
> > It splits the the headings line and for each heading sets that property of the object to the corresponding value.
> 
> can you output it as `left aligned` ? if yes, then u'd need none of those "pretty nasty regex", it becomes literally a 3 word readymade command.
> 
> if no, then maybe give it a second thought - find the max-width of column if possible and output according to that. the benefits are immense if u do lots of parsing of output.

So what actually happens is there is a chatty message logged to the event log 
It says something like 
```
"I read 123,567 rows of data from wibble.csv into tbl_wibble. There were previously 123,123 rows, Wibble requires 100,000 rows to process.  I calculated deltas and put them in another table. Deltas were
Adds Deletes Updates
---- ------- -------
 567     123     789
I moved wibble.csv into \date_time\uploads"
```
And this chugged along really nicely until someone said "Yesterday we only got 3/4 of the records for we expected for tbl_foobar and sure enough there in windows event log it says. 
```
I read 75,000 rows of data from foobar.csv into tbl_foobar. There were previously 101,010 rows, Foobar requires 20,000 rows to process.  I calculated deltas and put them in another table. Deltas were
Deletes 
-------
   26010  
Extracts from foobar are not archived. 
```
So someone asks if we can get stuff from the log, and pull out the rows, the table, the adds, deletes, and updates, and the destination where the file went - if we kept it.  So I have to read the preable, postamble (if it has the file destination) and figure out which of the 3 columns are present. 
So I wrote the a regex which I doubt anyone else can follow - and I really should use (?x) , write my regex as a multi-line string with inline comments but ... time, but I have something which gives whoever a list of what got logged as processed in the last day, and why a broken file wasn't rejected.  
What we should have done was added a table to our database for the load to put all this into and logged it that way, because you know that some will want something changed that breaks the regex.  It's supporting evidence for Snover's well known thing about you pipe text into something because the thing that wrote the text didn't give you quite what you wanted to so have to reverse engineer the text back to the data.

**Comment by goyalyashpal** [comment]
> The user is either (a) sitting in power shell (b) Invokes PowerShell and runs your app, then exits, or (c) runs `pwsh yourapp -parameters` from their existing shell.

aah, got it. thats where u r misunderstanding things. 

no, the user invokes directly as `myapp` from any shell. they dont even know its written in what lang.

**Comment by goyalyashpal** [comment]
> BUT don't try to get the PowerShell folks to do something because it will make parsing better, no-one is going to see that as a reason to lift a finger

well, it requires a simple: "**we** won't be doing this, but PRs welcome", reply from the team which will indicate that yeah they will be willing xo review and accept it. this quoted verbosity doesnt result in any conclusion.

**Comment by rhubarb-geek-nz** [comment]
> well, it requires a simple: _"**we** won't be doing this, but PRs **welcome**"_, reply from the team which will indicate that yeah they will be willing to review and accept it. this quoted verbosity doesnt result in any conclusion.

The answer to whether something will be done is normally answered by the relevant working group and that takes time. These initial discussions serve a number of purposes.

1. helps people find out if there is already a solution or work around available
2. tease out many of the technical details and implications from PR which are often vague, incomplete or misunderstood
3. allows the person raising the PR to plead their case as to why it should be implemented

So the end result is that much of the analysis has already been done before it gets to the working group.

**Comment by jhoneill** [comment]
> > The user is either (a) sitting in power shell (b) Invokes PowerShell and runs your app, then exits, or (c) runs `pwsh yourapp -parameters` from their existing shell.
> 
> aah, got it. thats where u r misunderstanding things.
> 
> no, the user invokes directly as `yourapp` from any shell. they dont even know its written in what lang.

Ah, well if you've got PowerShell compiled into another app which emits strings, then I think the stock answer is that you can make your users lives easier if you give them a switch for "Output parser friendly but less human readable".   
There is still an argument that if you had something that was screen scraper friendly it would help in some cases, and that's not wrong, it's just not likely to get much traction. 


> 
> > BUT don't try to get the PowerShell folks to do something because it will make parsing better, no-one is going to see that as a reason to lift a finger
> 
> well, it requires a simple: _"**we** won't be doing this, but PRs **welcome**"_, reply from the team which will indicate that yeah they will be willing to review and accept it. 

And there is the problem because someone goes "hey I just added something to this function", which is the easy part, and then tests need to written / changed documentation needs to be updated, and what's a few hours work for someone to code needs a multiple of that to integrate it into the produce. Hence my advice that a small incremental improvement in the ability parse stuff   may not meet the bar for getting into the product even if someone else does the small part of writing the code.  

Format-Table itself outputs objects found under `Microsoft.PowerShell.Commands.Internal.Format`  (That's why you can do `$t = $x | ft'` and then  `$t | out-string -width 80`  and `$t | out-string -width 240` make different text).  So we're talking about  either changing those  - or having a preference variable for the `gap` used they are rendered - but that would need to be an environment variable for a compiled app to see it. If people see different output from remote sessions doing the same thing because the preference differs on the clients is that a good thing or a bad thing?  If I set a preference because I like 4 spaces between my columns and break someone's prayer-based parser because it assumes one doing it to please me as a user isn't automatically good.  So what looks like a simple request begets a shed load of work.

None of which says the idea is bad, but the argument for doing the work doesn't look to me like one to convince the people it needs to. (I used to be one of those people).

**Comment by goyalyashpal** [comment]
> or having a preference variable for the `gap` used they are rendered - but that would need to be an environment variable for a compiled app to see it

no, that will be unnecessary. this was how things used to be in posix environ, but here and now, it would be too much overkill. my thought was just being able to specify it as a parameter in the output table command.

**Comment by jhoneill** [comment]
> > or having a preference variable for the `gap` used they are rendered - but that would need to be an environment variable for a compiled app to see it
> 
> no, that will be unnecessary. this was how things used to be in posix environ, but here and now, it would be too much overkill. my thought was just being able to specify it as a parameter in the output table command, which can easily be kept in sync by using another global constant in the script/app itself.

Putting it format-table is the simple and obvious solution. But that means changing the objects format-table outputs, and if you do format-table in a remote session and send the new objects (even without setting the gap)  back to an older version of PowerShell does that cause the renderer to crash? It's those sorts of questions which someone has to deal with when adopting it from a contributor PR, and TBH most contributors wouldn't consider.

**Comment by SeeminglyScience** [comment]
FYI the structure of formatting is *not* part of the breaking change contract. Attempting to parse it is not a supported scenario and can be broken even in patch releases.

If you're trying to read stdout from PowerShell and want something parseable I would suggest using the `-OutputFormat XML` parameter

**Comment by theJasonHelmick** [comment]
@goyalyashpal -- Thank you for this issue. The interactive WG has reviewed this issue.  If you need parsable output, the  functionality you are looking for already exists in the ConvertTo-CSV cmdlet. Use the **Delimiter** parameter to specify the separator string.

**Comment by trackd** [comment]
caveat, this is not really supported and can break.

I have recently been spelunking in the formatdata for a bit..

And i saw that you asked to see some samples of how to parse

Parsing the formatted output is not the way to go imo..

option 1,
get the formatdata for the object
[ConvertTo-TableFormat](https://gist.github.com/trackd/6cba343518c2fa7f4b13b8508a1e4812) this has some drawbacks as it doesn't really handle `[ICollection]` stuff all that well. 
most things work fine, probably least likely to break.

option 2,
use the Format-Table objects (`FormatStartData`, `FormatEntryData`)
[simple example](https://gist.github.com/trackd/bde8266b15e50c71246696517f04ca48)
[ConvertTo-MarkdownTable](https://gist.github.com/trackd/2c670e3c1a127ab32d885a68168c06a9) this is just an experiment that im messing around with...
[Format-SpectreTable](https://pwshspectreconsole.com/reference/formatting/format-spectretable/) uses spectre.console lib, which has some nice options for tables.

note,
while you can certainly use ConvertTo-CSV, it does add alot of _stuff_ that you probably dont care about. and the output is quite different
```ps1
gps | select -First 1 | ConvertTo-Csv
# vs
gps | select -First 1 | ft
```

sometimes you can do this,
```ps1
$a = gps
$a | Select-Object -Property $a[0].PSStandardMembers.DefaultDisplayPropertySet.ReferencedPropertyNames | ConvertTo-Csv
```
but `DefaultDisplayPropertySet` is pretty hit and miss with the implementation..

it would be nice if there was an easier way to use the format engine for custom stuff.
