### ISSUE TITLE
Cannot run pwsh script but bash can.

### ISSUE THREAD

**Issue by rdebath** [PowerShell/PowerShell#24090]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Try to start a script with a `#!` for powershell.
Might have to do it on Linux ARM machine from Azure.

### Expected behavior

```console
debian@DebianARM:~$ pwsh
PS /home/debian> head -1 ~/agent/az-agents
#!/usr/bin/env pwsh
PS /home/debian> ~/agent/az-agents
Find agents in the pool 'Default' on 'https://dev.azure.com/TVisionDev/'
98      online  True    None    32      None    None    DebianARM
128     online  True    None    500     None    10.0.19045      Blade01
130     online  True    None    500     None    10.0.19045      Blade02
131     online  True    None    250     None    10.0.19045      Blade03
```

### Actual behavior

```console
debian@DebianARM:~$ pwsh
PS /home/debian> head -1 ~/agent/az-agents
#!/usr/bin/env pwsh
PS /home/debian> ~/agent/az-agents
x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
PS /home/debian> debian@DebianARM:~$
debian@DebianARM:~$ ~/agent/az-agents
Find agents in the pool 'Default' on 'https://dev.azure.com/TVisionDev/'
98      online  True    None    32      None    None    DebianARM
128     online  True    None    500     None    10.0.19045      Blade01
130     online  True    None    500     None    10.0.19045      Blade02
131     online  True    None    250     None    10.0.19045      Blade03
```

### Error details

```console
PS /home/debian> get-error
PS /home/debian>
```

### Environment data

```powershell
PS /home/debian> $PSVersiontable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Debian GNU/Linux 12 (bookworm)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/debian>
```

**Comment by rhubarb-geek-nz** [comment]
Start with the simplest case

```
$ cat foo
#!/usr/bin/env pwsh

Write-Output 'Hello World'
```

Running from bash

```
$ ./foo
Hello World
```

Running from PowerShell

```
$ pwsh
PowerShell 7.4.4
PS> ./foo
Hello World
```

So it is able to run the script.

What it looks like is a situation where the script is trying to run an x64 compiled binary.

```
$ ldd $(which pwsh)
        linux-vdso.so.1 (0x0000ff0230aae000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ff02309f0000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ff02309c0000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ff02307a0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ff0230700000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ff02306c0000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ff0230510000)
        /lib/ld-linux-aarch64.so.1 (0x0000ff0230a71000)
```

> x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

This does not look like a Debian path

```
$ ls -ld /lib*
lrwxrwxrwx 1 root root 7 Jul  4  2023 /lib -> usr/lib
```

It looks more like a path compiled for RedHat or Mariner

```
$ ls -ld /lib*
lrwxrwxrwx 1 root root 7 Jan 23  2024 /lib -> usr/lib
lrwxrwxrwx 1 root root 7 Jan 23  2024 /lib64 -> usr/lib
```

**Comment by 237dmitry** [comment]
In my environment:

```
$ ldd /opt/pwsh/pwsh
linux-vdso.so.1 (0x000077b5896ed000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x000077b5896b0000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x000077b5896ab000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000077b589400000)
libm.so.6 => /usr/lib/libm.so.6 (0x000077b589311000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000077b5892e3000)
libc.so.6 => /usr/lib/libc.so.6 (0x000077b5890f2000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x000077b5896ef000)
```

/lib64 is the symlink to /ust/lib:

```
$ (Get-Item /lib64).Target
usr/lib
```

**Comment by rdebath** [comment]
The path `/lib64/ld-linux-x86-64.so.2` is the Linux standard path for the `x86-64` ELF dynamic linker.
It is correct for ALL x86-64 ELF versions of Linux.
It should not be referenced on an ARM64 machine; the equivalent on arm64 is `/usr/lib/ld-linux-aarch64.so.1`.
It is hardcoded into a binary as an interpreter for dynamic linked ELF executables.

The `x86_64-binfmt-P` executable is part of qemu, which has been setup for running some `i386` executables, slowly. No library support for `x86-64` executables has been installed and for obvious reasons I don't want to run `x86-64` executables on an Arm processor (Though I expect static programs might work). I especially don't want to run a version of `pwsh` compiled for `x86_64` on `aarch64`. 

Your `Hello World` script also fails.

More details suggested by your responses ...
```
debian@DebianARM:/tmp/test$ dpkg -S x86_64-binfmt-P
qemu-user-static: /usr/libexec/qemu-binfmt/x86_64-binfmt-P
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$ file /usr/libexec/qemu-binfmt/x86_64-binfmt-P
/usr/libexec/qemu-binfmt/x86_64-binfmt-P: symbolic link to ../../bin/qemu-x86_64-static
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$ file `which qemu-x86_64-static`
/usr/bin/qemu-x86_64-static: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=125ba3a4f68351d2c9c3534c69adc2bf1479501f, for GNU/Linux 3.7.0, stripped
debian@DebianARM:/tmp/test$

debian@DebianARM:/tmp/test$ chmod +x foo
debian@DebianARM:/tmp/test$ ./foo
Hello World
debian@DebianARM:/tmp/test$ pwsh ./foo
Hello World
debian@DebianARM:/tmp/test$ pwsh
PS /tmp/test> ./foo
x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
PS /tmp/test> exit
debian@DebianARM:/tmp/test$ cat foo
#!/usr/bin/env pwsh

Write-Output 'Hello World'
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$ ldd $(which pwsh)
        linux-vdso.so.1 (0x0000ffffa14a5000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffa13f0000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffa13c0000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffffa11a0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffa1100000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffffa10c0000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffa0f10000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffa1468000)
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$ file hello
hello: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, no section header
debian@DebianARM:/tmp/test$ ./hello
Hello World!
debian@DebianARM:/tmp/test$
debian@DebianARM:/tmp/test$ file /bin/cat
/bin/cat: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=67c0f2beecec29f5643100ff22b6eef7af5c1ad1, for GNU/Linux 3.7.0, stripped
debian@DebianARM:/tmp/test$ ldd /bin/cat
        linux-vdso.so.1 (0x0000ffff84848000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff84630000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff8480b000)
debian@DebianARM:/tmp/test$


```

**Comment by rhubarb-geek-nz** [comment]
I suspect it is a `$env:PATH` issue.

What does Get-Command return?

```
PS> Get-Command pwsh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pwsh                                               0.0.0.0    /opt/microsoft/powershell/7/pwsh
```

Is it pointing at a version intended for qemu?

**Comment by rdebath** [comment]
Nope, I haven't intentionally installed any x86_64 executables, just a couple of i386 ones, there's only one pwsh in $PATH, it's aarch64.

OTOH: It's not in $PATH, but pwsh seems to have added a directory to the start of $env:PATH and this new directory has x86_64 files ... for some reason.

```
debian@DebianARM:~/agent$ echo $PATH
/home/debian/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/debian/.dotnet:/home/debian/.dotnet/tools
debian@DebianARM:~/agent$ which -a pwsh
/home/debian/.dotnet/tools/pwsh
debian@DebianARM:~/agent$ file /home/debian/.dotnet/tools/pwsh
/home/debian/.dotnet/tools/pwsh: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=f71a297ddc1eba7dde5fe55e575f6ac6b5a4ce36, stripped
debian@DebianARM:~/agent$
```
```
PS /home/debian/agent> Get-Command pwsh | fl

Name            : pwsh
CommandType     : Application
Definition      : /home/debian/.dotnet/tools/.store/powershell/7.4.1/powershell/7.4.1/tools/net8.0/any/unix/pwsh
Extension       :
Path            : /home/debian/.dotnet/tools/.store/powershell/7.4.1/powershell/7.4.1/tools/net8.0/any/unix/pwsh
FileVersionInfo : File:             /home/debian/.dotnet/tools/.store/powershell/7.4.1/powershell/7.4.1/tools/net8.0/any/uni
                  x/pwsh
                  InternalName:
                  OriginalFilename:
                  FileVersion:
                  FileDescription:
                  Product:
                  ProductVersion:
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:

```

```
debian@DebianARM:~/agent$
debian@DebianARM:~/agent$ file /home/debian/.dotnet/tools/.store/powershell/7.4.1/powershell/7.4.1/tools/net8.0/any/unix/pwsh
/home/debian/.dotnet/tools/.store/powershell/7.4.1/powershell/7.4.1/tools/net8.0/any/unix/pwsh: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=f41ff499f9f18f8c74413c4b50ad412e05168693, stripped
debian@DebianARM:~/agent$

```

**Comment by mklement0** [comment]
> `pwsh` seems to have added a directory to the start of `$env:PATH`

`pwsh` - by design - _prepends its own installation directory (`$PSHOME`) to `$env:PATH`_, presumably in an effort to ensure that launching commands based on `pwsh` targets the same PowerShell binary that was used to start the session.

**Comment by rhubarb-geek-nz** [comment]
Are you using a dotnet tool version of PowerShell rather than a standard installation?

Yes, it is unfortunate that after three years we still don't have Debian ARM packages, [I roll my own](https://github.com/rhubarb-geek-nz/PowerShell/releases/tag/7.4.4).

**Comment by rhubarb-geek-nz** [comment]
Alas this seems to be a feature of PowerShell as a dotnet tool.....

```
$ dpkg --print-architecture
arm64
$ dotnet tool restore
Tool 'powershell' (version '7.2.21') was restored. Available commands: pwsh

Restore was successful.
$ dotnet pwsh
PowerShell 7.2.21
Copyright (c) Microsoft Corporation.

Type 'help' to get help.

PS> get-command pwsh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pwsh                                               0.0.0.0    /home/bythesea/.nuget/packages/powershell/7.2.21/tools/net6.0/any/unix/pwsh

PS> file  /home/bythesea/.nuget/packages/powershell/7.2.21/tools/net6.0/any/unix/pwsh
/home/bythesea/.nuget/packages/powershell/7.2.21/tools/net6.0/any/unix/pwsh: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=91aca470021b45d780350f8d6e16c30945c61a32, for GNU/Linux 2.6.32, stripped
```

**Comment by mklement0** [comment]
As a data point: on _macOS_, `dotnet tool install -g PowerShell` correctly installs an ARM64 binary.

**Comment by rhubarb-geek-nz** [comment]
> As a data point: on _macOS_ on an M1+ machine, `dotnet tool install -g PowerShell` correctly installs an ARM64 binary.

Maybe, but run that pwsh, then in that PowerShell session run

```
Get-Command pwsh
```

**Comment by mklement0** [comment]
You're correct:

It is only the _stub_ binary that is ARM.

The executable ultimately invoked - `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh` - is indeed an x86-64 executable.

**Comment by rdebath** [comment]
@mklement0 The version under ~/.dotnet/tools/pwsh is not a stub, it's a full executable. If you remove the x86-64 binary it'll be used to run "nested" script commands and everything seems to work fine. 

Presumably the one in the "installation directory" should be the real one and the tools directory should have a symlink following the usual pattern.

**Comment by mklement0** [comment]
@rdebath, it may be a full executable, but, as I've just discovered, it delegates first to `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/Microsoft.PowerShell.GlobalTool.Shim.dll` and then to `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh.dll` - at least on my Mac:

* If you enter an interactive session and execute `[Environment]::GetCommandLineArgs(0)`, you'll see the latter path, i.e. seemingly the actual assembly.
* If you temporarily rename the `$HOME/dotnet/tools/.store/powershell/7.4.4` folder and then try to enter an interactive session, it'll fail, complaining about not finding the former (shim) assembly path.

In other words: It looks like `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/Microsoft.PowerShell.GlobalTool.Shim.dll` picks the target binary, and it inappropriately picks an x86 binary on ARM platforms, and _no ARM binaries are even part of the NuGet package_.

---

The curious thing is that on my Mac the `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh` _executable_  (not the assembly) refuses to even execute on my Mac, even though it is the path reported by `Get-Command pwsh` and is what is invoked if I try a CLI call such as `pwsh { Get-Date }`. I get `Exec format error`

I _can_ invoke the `.dll` via the `dotnet` CLI (`dotnet $HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh.dll`)
The `.dll` is a x86 binary also, albeit of a different kind: `file` reports:
`PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows` (!)

**Comment by rdebath** [comment]
@mklement0 
That sounds exactly right. Dotnet core programs (eg: pwsh) are constructed in a very weird way, even on Windows. The `pwsh` executable is a "native" executable compiled down to x86 or Arm machine code, however, it is not your final program, it's part of a high performance interpreter for the "msil" (or "cil") code that C#, VB, F# etc are compiled to. The DLL files are labeled as a an x86 assembly but in reality, while it may contain x86 machine code, it also contains "msil machine code" which is translated to "native" code at run time (or install time by ngen?).

As for your "Exec format error", this is the symptom that I'd get if I removed the qemu support for foreign binaries. The `file` command should be able to identify the "magic" numbers in the executable's header block and display which CPU it's intended for like it does the ".Net assembly" files.

One tiny thing, I don't think the shim is "picking" the x86 binary, it's just passing "pwsh" to a "system()" or "execvp()" call which picks the first "pwsh" in the modified PATH environment variable. For my example the "hello" script is actually executed as a binary file _by the kernel_. The "#!" is a magic number that the kernel recognises as a flag to run the command "/usr/bin/env" as an interpreter for the file. The "env" command then does a path search for "pwsh" by calling "execvp()" to run it.

**Comment by mklement0** [comment]
Thanks for the background info, @rdebath.

Yes, the kernel, based on shebang line `#!/usr/bin/env pwsh`, picks the first `pwsh` binary in `$env:PATH`.

Because of the way the `$HOME/dotnet/tools/pwsh` shim operates (the exact mechanism is unclear to me, but `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/Microsoft.PowerShell.GlobalTool.Shim.dll` must be involved), it is `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix` that is made the first `$env:PATH` entry when you first enter a .NET tool-installed PowerShell session.

Thus, if you invoke a shebang line-based shell script from inside a session, it is the _platform-inappropriate_ binary at `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh` that is invoked.

Based on what you're saying about _assemblies_, it  may be sufficient for  `$HOME/dotnet/tools/pwsh` to be architecture-appropriate (which it is), as long as it serves as the entry point, correct?

If so, the fix should be simple: Instead of prepending `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix` to `$env:PATH`, prepend `$HOME/dotnet/tools` instead.
(While `$HOME/dotnet/tools` likely already is in `$env:PATH` _somewhere_, it needs to come _first_ to reliably target the `pwsh` in that location by filename only; this is somewhat unfortunate, because at least hypothetically it can change the effective binary for other tools too, if they have namesakes that happened to come earlier in the original `$env:PATH`).


To demonstrate: If I enter a `$HOME/dotnet/tools/pwsh` session and then execute the following before invoking shebang line-based scripts or making direct `pwsh` calls, the problem goes away:

```powershell
$env:PATH = "$HOME/.dotnet/tools:$env:PATH"
```

**Comment by rdebath** [comment]
If you look in the source to this repo the `Shim` seems to be something to choose either "Windows" or "Unix". I don't see how it's supposed to choose "x86" vs "Arm" on either of them though.

Assuming that's the case then `unix/pwsh` should be something that'll run correctly on any supported Unixish. Looking down the list of runtimes, the only thing I can think of that has any chance is a shell script. 
Based on the "shim" it should perhaps be something like this:
``` sh
#!/bin/sh -
exec dotnet "$0.dll" "$@"
```

I don't like the idea of putting the Dotnet tools directory in front, it would interfere with the user putting override "stuff" in $HOME/bin for tools other than `pwsh`.

And yes, IIRC the .Net assembly DLLs where designed to be processor independent so AMD or Intel specific optimisations could be done. They were turned into fat binaries to improve performance, but `ngen` is supposed to be better than the generic native CPU code in the fat binary.

**Comment by mklement0** [comment]
> I don't like the idea of putting the Dotnet tools directory in front, it would interfere with the user putting override "stuff" in $HOME/bin for tools other than pwsh.

I agree.

Replacing the binary at, e.g., `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix/pwsh` with a shell script with the content in your previous comment should work for Unix-like platforms, but there's no equivalent solution for Windows, unfortunately (batch files require extension `.bat` or `.cmd`, whereas `.exe` is needed).

Similarly, placing a `pwsh` symlink to `$HOME/dotnet/tools/pwsh` in  `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any` and prepending the latter to `$env:PATH` seemingly works only on Unix-like platforms, not analogously on Windows (the fundamental problem there is that creating a symlink by default requires _elevation_, but even then the invocation doesn't work).

**Comment by rdebath** [comment]
Actually it looks like Windows ARM has an i386 emulator turned on by default so you can use the x86 version. For example when setting up a windows VM on an M1 Mac a little while ago I used a 1995 copy of `gzip.exe` without thinking about it and it worked fine. Also there are a lot of `exe` installers which presumably have an i386 stub so they work on both 32bit and 64bit Intel. The few I "tried" also worked. The failures I had seemed to be to do with native x86 DLLs being dropped into system directories, yeah, that sounds like a bad idea.

Not sure if it has an x86-64 emulator ... not sure if it matters.

The symlink is mainly just an efficiency (or cleanliness) thing, for eg, so you don't get this happening again.

**Comment by mklement0** [comment]
> Actually it looks like Windows ARM has an i386 emulator turned on by default so you can use the x86 version.

That doesn't work for me in my VM running the following: Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.3880): trying to run `pwsh` from inside a .NET tool-installed `pwsh` session _fails_.

At this point it seems that we don't have a potential cross-platform solution for the PowerShell bug at hand.

**Comment by rdebath** [comment]
What if you swipe the `pwsh.exe` from a 32bit Intel windows build and try that on the ARM64 ?

**Comment by mklement0** [comment]
I don't have access to that and I don't know what you mean by _32bit intel C++ version of the shell script_, but it's also not clear how that would be a general bug fix.

Taking a step back:

* Neither the title of this issue nor the lengthy comments exchange here make it readily obvious what the problem is.

* The gist of the problem is: Invoking a `pwsh` child process (by file name only) from inside a .NET tool-installed PowerShell version is broken on ARM platforms, which is obviously a  bug.

While I'm personally somewhat interested in the underlying technical problems (and have learned from your responses here), I'm not personally invested in getting this problem fixed, as I've never used PowerShell as a .NET tool.

If _you_ are invested in a fix, I suggest creating a new issue that provides a focused summary of the problem and closing this issue.

**Comment by rdebath** [comment]
Okay, I guess the core problem is that PowerShell corrupts the PATH environment variable when running an external command.
Usual best practice is to **_never_** touch it unless you are completely recreating it. (Usually for security reasons)

This means the reason for prepending a random directory to the PATH needs to be revisited as I really can't see a good reason to do it. Some vague requirement to be sure you're using "the right version" would be solved by using the full pathname of the executable were it actually matters. It doesn't matter for running general external commands. (Is someone using `$PATH` when they should be using `$PSModulePath` ?)

That is what has caused this hunt for a "fully cross-platform executable"; after saying it like that I agree it's the wrong path. A `32bit Intel Windows executable, presumably written in C++, to run on the WoW64 i386 emulator in ARM64 Windows` is not a good example.

After all, the current working solution is to simply remove the x86-64 executable, losing nothing of value.

PS: Sorry for encouraging you down the rabbit hole. :grin:

**Comment by mklement0** [comment]
No worries re rabbit hole; as noted, it's been a learning experience for me.

As for how to frame the issue at hand:

* The .NET tool-installed PowerShell version acts no differently with respect to the `$env:PATH` modification (prepending its own installation directory) than a regular installation.
  * While I agree with you that this - clearly by-design - behavior is questionable, changing it now would be a breaking change; it would only be entertained if it were deemed to fall into [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) (I don't know the answer to that.)
  * If a change were to be made, existing code will behave differently in two scenarios:
    * If a _different_ `pwsh` comes first in `$env:PATH`, it is the latter that is invoked by a name-only call rather than the one hosting the current session.
    * If _no_ `pwsh` is in `$env:PATH` (which is perhaps unlikely), name-only `pwsh` calls simply fail.

* However, even if this change were made, the problem doesn't fully go away:
  * `$PSHOME`, i.e. the automatic variable reflecting the installation directory, would still point to, e.g., `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix`, where the _wrong_ binary is present.'
  * Thus, using `& $PSHOME/pwsh` in an effort to explicitly invoke the same binary that underlies the current session would still misbehave (and _removing_ that binary wouldn't help and result in unconditional failure).

I don't know if setting `$PSHOME` to `$HOME/dotnet/tools` (which cannot be done from PowerShell code) would have ill effects, but there are two challenges:
* Existing code may go looking for the assemblies that ship with PowerShell there, which won't be there.
* The invocation of the target `pwsh.dll` assembly via an external `dotnet` process means that the former doesn't know about the binary that served as the original entry point and whose directory path `$PSHOME` should be set to, though I suppose it could examine the parent process.

**Comment by mklement0** [comment]
Turns out I reported this problem 3 years ago, albeit macOS-focused and with less technical insight - issue was closed due to inactivity:
* #12205

Another closed-due-to-inactivity issue with the same root cause, in the context of `Start-Job`:
* #18139

Note that `Start-Job` apparently explicitly uses (the equivalent value of) `$PSHOME` to locate `pwsh`, which would be fixed by setting the latter to `$HOME/dotnet/tools`

**Comment by rdebath** [comment]
[This](https://github.com/PowerShell/PowerShell/issues/4194) seems to be why the path is prefixed.
This "fix" was broken when the executable was renamed.

**Comment by mklement0** [comment]
That's a good find, @rdebath - I didn't know the backstory.
Let me try a **summary** of sorts:

* The current behavior of prepending PowerShell's own installation directory to the in-process value of `$env:PATH` on startup was introduced at a time when PowerShell (Core) and Windows PowerShell used the same executable file name, `powershell.exe`, in an effort to prevent a name-only call to `powershell.exe` made (from PowerShell (Core)) from accidentally invoking _Windows PowerShell_'s CLI.

  * By definition, this problem only existed on Windows.
  * Even there, the problem went away when `powershell.exe` was renamed to `pwsh.exe` 

* Because of how PowerShell (Core) _as a .NET tool_ is implemented, this `$env:PATH` startup modification now breaks name-only `pwsh` invocations on ARM machines, among other scenarios, regardless of platform type (Windows, macOS, Linux) and, if memory serves, also on Intel Macs (because the x86_84 binary invoked is for _Linux_).

  * The crux of the problem is that the executable that `$PHSOME/pwsh` points to _from inside a session_ is an _inappropriate executable_ on such machines; while seemingly meant _not_ to be used, its accidental use is quite likely:

    * On _entering_ a .NET tool-installed PowerShell session this is _not_ a problem, because the distinct `pwsh` executable that serves as the .NET tool-installed entry point (`$HOME/tools/.dotnet/pwsh`) _is_ platform- and architecture-appropriate. Via a helper assembly (`Microsoft.PowerShell.GlobalTool.Shim.dll`) it synchronously launches a child process for the `dotnet` CLI with assembly `pwsh.dll`. That is, it effectively runs PowerShell as a _runtime-dependent_ (framework-dependent) application, with `dotnet` acting as the platform- and architecture-appropriate entry point that invokes an _abstractly_ platform-appropriate `pwsh.dll` assembly inside the unpacked NuGet package (the distinction is only between Windows and Unix-like platforms). It is the latter's directory path (e.g. `$HOME/dotnet/tools/.store/powershell/7.4.4/powershell/7.4.4/tools/net8.0/any/unix`) that becomes the value of `$PSHOME` in the new session, _not_ that of the original entry point (`$HOME/tools/.dotnet`).
  
    * Once _inside_ such a session, however - due to the `$env:PATH` modification - the inappropriate `$PHSOME/pwsh` executable typically _is_ involved, namely when a `pwsh` _chid process_ is invoked. Specifically, it _breaks the following scenarios_:
      * (a) a name-only `pwsh` call, including via `$env:PATH`-based shebang lines  (the use case that prompted this issue)
      * (b) an attempt to call the same executable that underlies the current session: `& $PSHOME/pwsh`
      * (c) an attempt to use `Start-Process`, because PowerShell explicitly looks in the same directory reflected in `$PSHOME`, which is the directory in which its ultimate startup assembly, `pwsh.dll`, is located.

---

Thus, there are two distinct problems, which can be tackled separately:

* Revert the startup `$env:PATH` modification, as it is no longer needed.

  * This would implicitly fix problem (a), but wouldn't fix (b) and (c)

  * It is technically a breaking change, and could change the behavior of existing code in the following - exotic - scenarios:
     * If a _different_ `pwsh` comes first in the (now unmodified) `$env:PATH`, it is the latter that is invoked by a name-only call rather than the one hosting the current session.
     * If _no_ `pwsh` is in `$env:PATH` (which is perhaps unlikely), name-only `pwsh` calls simply fail.


* Ensure that `$PSHOME/pwsh` points to a platform- and architecture-appropriate entry point.

  * This is needed to fix (b) and (c), and may require re-architecting how PowerShell is installed as a .NET tool.

  * Replacing the inappropriate executable with a _symlink_ that point to `$HOME/tools/.dotnet/pwsh` - if even feasible from an installation standpoint - works on Unix-like platforms, but not on Windows (where symlink creation by default requires _elevation_; while creating a _hardlink_ doesn't require elevation, it doesn't work as-is and would require additional logic)

**Comment by rdebath** [comment]
That sounds pretty close, though ...
* I note that there are two executables $PSHOME/pwsh.exe and $PSHOME/pwsh for windows and unix which may change things.
* It'd be a really bad idea to try your previous idea and change $PSHOME because a lot of other things reference off of it.

IMO it would nice if the executable in `$HOME/.dotnet/tools` could record the actual pwsh/pwsh.exe invoked by recording argv[0] (or /proc/self/exe on Linux) and pass that into pwsh for it to use internally. This should prevent `Start-Process` invoking the wrong one even in antagonistic cases.

**Comment by theJasonHelmick** [comment]
Thanks @rdebath for reporting this issue. The Interactive-WG agrees that there is a problem with the dotnet tool on ARM as described in this issue.  We were able to reproduce and we encourage the continued investigation to resolve.

**Comment by mklement0** [comment]
To summarize my understanding of how this was resolved by #24228:

* PowerShell will continue to prepend the directory in which the PowerShell executable is (in effect) located to `$env:PATH`
 
  * As noted, [the historical reason for doing so no longer applies](https://github.com/PowerShell/PowerShell/issues/24090#issuecomment-2267527201).

* For a .NET tool-installed version, both the directory prepended to `$env:PATH` and  the value reflected in `$PSHOME` have been changed to reflect the directory of the tool CLI's _entry point_.

In other words, the [previously stated caveat](https://github.com/PowerShell/PowerShell/issues/24090#issuecomment-2269544076) still applies:

> redefining `$PSHOME` is ill-advised: while it would make `& $PSHOME/pwsh` work, it wouldn't allow you to reference `$PSHOME/powershell.config.json`, for instance, and, as previously stated, wouldn't allow you to find the assemblies that PowerShell ships with.

**Comment by SleepyFoxStudio** [comment]
This is still broken in the latest docker image i am using mcr.microsoft.com/dotnet/sdk:9.0.101-noble-arm64v8@sha256:002913b3125dd93b9a38cf640df27451975c75bf7207332c7cbf3946e556689e

with the following in my dockerfile

<pre>RUN pwsh -Command 'Write-Host ${env:PSHOME}'
RUN pwsh -Command 'Write-Host ${env:PATH}'
RUN pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA'</pre>

results in the following error 
<pre>#11 [ 8/10] RUN pwsh -Command 'Write-Host ${env:PSHOME}'
#11 1.562 
#11 DONE 1.7s

#12 [ 9/10] RUN pwsh -Command 'Write-Host ${env:PATH}'
#12 1.214 /usr/share/powershell/.store/powershell.linux.arm64/7.5.0-preview.5/powershell.linux.arm64/7.5.0-preview.5/tools/net9.0/any:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#12 DONE 1.3s

#13 [10/10] RUN pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA'
#13 1.392 ResourceUnavailable: Program 'pwsh' failed to run: An error occurred trying to start process '/usr/share/powershell/.store/powershell.linux.arm64/7.5.0-preview.5/powershell.linux.arm64/7.5.0-preview.5/tools/net9.0/any/pwsh' with working directory '/'. Exec format errorAt line:1 char:1
#13 1.406 + pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA
#13 1.406 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
#13 ERROR: process "/bin/sh -c pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA'" did not complete successfully: exit code: 1
------
 > [10/10] RUN pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA':
1.392 ResourceUnavailable: Program 'pwsh' failed to run: An error occurred trying to start process '/usr/share/powershell/.store/powershell.linux.arm64/7.5.0-preview.5/powershell.linux.arm64/7.5.0-preview.5/tools/net9.0/any/pwsh' with working directory '/'. Exec format errorAt line:1 char:1
1.406 + pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA
1.406 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
------
Dockerfile:22
--------------------
  20 |     RUN pwsh -Command 'Write-Host ${env:PSHOME}'
  21 |     RUN pwsh -Command 'Write-Host ${env:PATH}'
  22 | >>> RUN pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA'
  23 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pwsh -Command 'pwsh -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAaABlAGwAbABvACcA'" did not complete successfully: exit code: 1</pre>
