### ISSUE TITLE
After upgrading to pwsh 7.5.0 from 7.4.7 --> Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by Marc013** [PowerShell/PowerShell#24878]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After upgrading to pwsh 7.5.0 (via winget) from 7.4.7 pwsh crashes.

The problem persists after removing pwsh, rebooting, and reinstalling pwsh 7.5.0 using the fresh download _PowerShell-7.5.0-win-x64.msi_.
Removing pwsh 7.5.0, installing 7.4.7 (fresh download _PowerShell-7.4.7-win-x64.msi_), and upgrading to pwsh 7.5.0 does not fix the problem.

Going back to pwsh 7.4.7 allowed me to use pwsh again.

### Expected behavior

```console
pwsh 7.5.0 to start without any issue.
```

### Actual behavior

```console
pwsh 7.5.0 crashes.
```

### Error details

```console
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.d.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeModule.GetDefinedTypes()
   at System.Reflection.RuntimeModule.GetTypes()
   at A.C.a(System.Reflection.Assembly)
   at A.a.a(System.Reflection.Assembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(System.String)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at System.Management.Automation.ExecutionContext.LoadAssembly(System.String, System.String, System.Exception ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.FixFileName(System.String, System.String, System.String, System.String, Boolean, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(System.Management.Automation.PSModuleInfo, Microsoft.PowerShell.Commands.ModuleSpecification, System.String, Boolean, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Object, Boolean ByRef, System.String, System.Nullable`1<System.Management.Automation.PSLanguageMode>)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(System.String, System.Management.Automation.ExternalScriptInfo, System.Collections.Hashtable, System.Collections.Hashtable, ManifestProcessingFlags, System.Version, System.Version, System.Version, System.Nullable`1<System.Guid>, ImportModuleOptions ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.String, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(System.String, ManifestProcessingFlags, ImportModuleOptions, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

[process exited with code 3221225477 (0xc0000005)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.7
PSEdition                      Core
GitCommitId                    7.4.7
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Image](https://github.com/user-attachments/assets/97b78a6b-3827-4b75-82c1-44e221fd931c)

**Comment by Marc013** [comment]
Yep,
Issue is duplicate of https://github.com/PowerShell/PowerShell/issues/24435.
I also have _SentinelOne_ active.

**Comment by ryan-leap** [comment]
+1 - same crash, also have SentinelOne Agent.

**Comment by bdleedy** [comment]
+1 for SentinelOne

**Comment by livingod101** [comment]
+1 SentinelOne

**Comment by wmd0701** [comment]
+1 SentinelOne

**Comment by fluidmilan** [comment]
+1 SentinelOne

**Comment by Marc013** [comment]
We also experienced this issue.
After updating the SentinelOne agent to version `24.1.5.277` the issue was solved.

**Comment by trcoelho** [comment]
How to update SentinelOne agent?

**Comment by TatianaL-QA** [comment]
Still crashing. I have updated SentinelOne agent, and consulted with our support (as it's the company policy, not manageable by me) anyway, crash persists, and had to downgrade back to 7.4.7). Should I create new ticket?

**Comment by Jefftezos** [comment]
Same with SentinelOne

**Comment by towianisci** [comment]
Same with SentinelOne
I tried updating to the latest version in preview and it receives the same issue as the current version 5.7.0.
Downgraded to 7.4 .7
It is now working. Can you please pull this update so it does not break? Please investigate why they're having issues with Sentinel One. 

PowerShell 7.6.0-preview.2
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef, System.String ByRef)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(System.Reflection.Assembly, System.Management.Automation.PSModuleInfo)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.Reflection.Assembly, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.String, Boolean ByRef, System.String, Boolean)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(System.Management.Automation.PSModuleInfo, Microsoft.PowerShell.Commands.ModuleSpecification, System.String, Boolean, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Object, Boolean ByRef, System.String, System.Nullable`1<System.Management.Automation.PSLanguageMode>)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(System.String, System.Management.Automation.ExternalScriptInfo, System.Collections.Hashtable, System.Collections.Hashtable, ManifestProcessingFlags, System.Version, System.Version, System.Version, System.Nullable`1<System.Guid>, ImportModuleOptions ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.String, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(System.String, ManifestProcessingFlags, ImportModuleOptions, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

[process exited with code 3221225477 (0xc0000005)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by livingod101** [comment]
Update: Sentinel Agent was updated to version 24.1.277, after installing 7.5.0 and now it's working.

**Comment by RustyPhillips** [comment]
Upgrading to 24.1.5.277 fixed mine.

**Comment by TatianaL-QA** [comment]
I realized there are different releases:
WindowsOS 24.1.4.257 (Self-Managed Release)
WindowsOS 23.4.4.223 (Self & Sonicwall-Managed Release)
So yes, for Self-Managed Release update will help. But those having **Sonicwall-Managed** releases will suffer until the issue is fixed, because update does not help.

**Comment by bytesolid** [comment]
SentinelOne user. Upgrading to 24.1.5.277 fixed mine as well.

**Comment by jlthompson1-godaddy** [comment]
S1 Installed, same error when upgrading to 7.5.x

**Comment by Voltharion** [comment]
![Image](https://github.com/user-attachments/assets/19e5e20e-0a76-400b-8728-df92f3012f1a)

**Comment by mattpogue** [comment]
> After updating the SentinelOne agent to version `24.1.5.277` the issue was solved.

Can confirm the same here - after SentinelOne upgrade, both pwsh 7.5.0 and 7.6.0-preview2 are working as expected.

**Comment by Pandorin** [comment]
+1 SentinelOne version 24.1.4.257

**Comment by pedro-baptista** [comment]
+1 SentinelOne version 24.1.4.257

**Comment by humberto-isdr** [comment]
+1 SentinelOne version 24.1.4.257 🤕

**Comment by iBloodWorks** [comment]
+1 SentinelOne version 23.4.4.223

**Comment by CheetahChrome** [comment]
Not fixed until upgrading to 24.1.5.277

**Comment by aagirre92** [comment]
Same with SentinelOne version 23.4.223

**Comment by leetNightshade** [comment]
My IT updated me to version 24.1.4.257, and that did not fix the issue for me with Powershell 7.5.0. Reverted back to Powershell 7.4.7 to get around the issue for now.

**Comment by Nolwennig-Jeulin** [comment]
I update **SentinelOne** to `24.1.5.227` to fix it !🏆

**Comment by nucolas** [comment]
New SentinelOne agent doesn't fix it. I'm reverting back to version 7.4.7

**Comment by OddMathisenNOV** [comment]
It worked for `24.1.5.227`, but after updating to `24.1.4.257` it has started breaking again.

**Comment by OddMathisenNOV** [comment]
Interestingly, running `pwsh -NonInteractive` does not cause the issue.

**Comment by DD1TTY** [comment]
Updated to SentinelOne agent 24.1.277 and it fixed the issue. Thanks all!

**Comment by azh2o** [comment]
+1 upgraded to latest S1 agent

**Comment by longzheng268** [comment]
系统是Win10 22H2。

```
CLR: Assert failure(PID 2208 [0x000008a0], Thread: 14156 [0x374c]): !AreShadowStacksEnabled() || UseSpecialUserModeApc()
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp:7954 Image:
C:\Program Files\PowerShell\7\pwsh.exe

```

**Comment by MichaelPuckett2** [comment]
Same

PowerShell 7.5.2
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef, System.String ByRef)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(System.Reflection.Assembly, System.Management.Automation.PSModuleInfo)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.Reflection.Assembly, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.String, Boolean ByRef, System.String, Boolean)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(System.Management.Automation.PSModuleInfo, Microsoft.PowerShell.Commands.ModuleSpecification, System.String, Boolean, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Object, Boolean ByRef, System.String, System.Nullable`1<System.Management.Automation.PSLanguageMode>)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(System.String, System.Management.Automation.ExternalScriptInfo, System.Collections.Hashtable, System.Collections.Hashtable, ManifestProcessingFlags, System.Version, System.Version, System.Version, System.Nullable`1<System.Guid>, ImportModuleOptions ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.String, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

**Comment by BlueBull010** [comment]
+1 Also S1 in use. Good to know, as we have >4000 devices with S1 agent deployed, so we'll hold off on updating Powershell for the moment
