### ISSUE TITLE
Two double-quotes in inline expressions

### ISSUE THREAD

**Issue by ivanakcheurov** [PowerShell/PowerShell#3039]
Steps to reproduce
------------------
`"Fancy string - $('Hor"ray'.Replace('"', '""'))"`

Expected behavior
-----------------
Output: `Hor""ray`

Actual behavior
---------------
Output: `Hor"ray`

Environment data
----------------

```powershell
> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.14393.479
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.479
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

http://stackoverflow.com/questions/24242338/powershell-doubled-double-quotes-in-inline-expressions/24346886#24346886
`'""'` outputs `""` so I expect `"$('""')"` should also output `""` however it actually outputs `"`

**Comment by lzybkr** [comment]
I'm not sure this can be fixed, it would likely break existing scripts, especially because the workaround is to use more quotes.

My memory is a little fuzzy, but I believe I tried to fix this issue when rewriting the parser in V3. I don't recall specifics, but my original design was to tokenize the sub-expression during initial scanning of the string, and I think it would have naturally worked as you expect.

Unfortunately, due to backwards compatibility issues (then and now), we continue to work as it did in V1 and V2.

**Comment by briantist** [comment]
This looks related to #4543 and [this question on SO](https://stackoverflow.com/q/47877162/3905079).

**Comment by briantist** [comment]
@lzybkr your previous comment was from almost a year ago. Since then it seems like there are plenty of breaking changes going from Windows PowerShell to  PowerShell Core. 

This seems like the right time if there ever was one to fix the parser.

**Comment by lzybkr** [comment]
While we have taken breaking changes, I believe none of them fall under Bucket 1 or 2 in the [breaking change contract](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md).

I believe this one falls under Bucket 2: Reasonable Gray Area because I do think real world scripts depend on the current behavior.

**Comment by briantist** [comment]
@lzybkr thanks for that link, it's great to read that sort of guidance about breaking changes.

Based on the examples given, this does seem to fall under Bucket 2.

But based on the description of each bucket, I think it falls under Bucket 3:

> Change of behavior that customers could have depended on, but probably wouldn't.

I think it's unlikely that existing scripts would have depended on this behavior. I believe it's far less likely that authors used what is clearly incorrect/unbalanced quotes as a workaround rather than opt to refactor or simplify (use the `-f` operator, pre-assign what was in a sub-expression to a variable, etc.).

Additionally even if it does fall under Bucket 2:

>Judiciously making changes in these type of features require judgement: how predictable, obvious, consistent was the behavior?

This behavior is not predictable, obvious, or consistent.

---
It would be interesting to take a large corpus of public scripts (PSGallery, TechNet Gallery, GitHub) and test our assumptions; see how much code is out there that depends on this specific parsing behavior (this would be easiest to do if we had a version of the parser with the fix, as we could run each parser against the same code and really quickly catch situations where it breaks).

**Comment by lzybkr** [comment]
I do think the behavior is predictable and consistent, but not necessarily obvious. By consistent, I mean, one could write a specification for how it works, and it would be slightly weird, but easily explained.

#### Quick attempt at a specification:

The parser scans the characters in string, replacing 2 quotes with 1. Nested sub-expressions are processed in a similar manner after this replacement.

#### Proof that this is correct

Use the following function to generate deeply nested expressions:

```powershell
function Test-Quotes
{
    param(
        [ValidateRange(1,16)]
        [int]
        $nestedExprs = 1,
        
        [ValidateRange(1,65536)]
        [int]$quoteCount = [math]::Pow(2, $nestedExprs))

    $prefix = '"$('
    $suffix = ')"'
    $actualExpr = "'" + ('"' * $quoteCount) + "'"
    $expr = $prefix * $nestedExprs + $actualExpr + $suffix * $nestedExprs
    $val = Invoke-Expression $expr
    "val: <$val> expr: = $expr"
}
```

With this function, I can validate my explanation above, e.g.:

```
#23 PS> 1..8 | Test-Quotes
val: <"> expr: = "$('""')"
val: <"> expr: = "$("$('""""')")"
val: <"> expr: = "$("$("$('""""""""')")")"
val: <"> expr: = "$("$("$("$('""""""""""""""""')")")")"
val: <"> expr: = "$("$("$("$("$('""""""""""""""""""""""""""""""""')")")")")"
val: <"> expr: = "$("$("$("$("$("$('""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""')")")")")")"
val: <"> expr: = "$("$("$("$("$("$("$('""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""')")")")")")")"
val: <"> expr: = "$("$("$("$("$("$("$("$('""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""')")")")")")")")"
```

You can see that the result is always a single quote when there are `n` nested expressions and `2^n` double quotes inside the inner single quoted string.

So I think this is predictable and I think my explanation is easily understood. But it's definitely not obvious.

Testing your assumptions here is hard. You can't really run a large corpus of scripts because most scripts will fail to run properly, or it is difficult to determine if they ran correctly, or if they even hit the code in question.

You can analyze a script with the Ast - and that wouldn't require a new parser - but I'm struggling to think of what exactly you would look for - it is difficult to infer intent. At best you could flag scripts that *might* rely on the existing behavior.

**Comment by lzybkr** [comment]
I can elaborate some on my original design.

When I rewrote the parser, I originally invoked the tokenizer recursively in nested expressions - because that seemed like the obvious way to do it.

I broke real world scripts, and one case that convinced me I had to mimic how the V1/V2 parser worked.  It was not easy to mimic the old parser *and* keep the extents correct (the old parser did not have extents.) You can see that complexity in the [tokenizer](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/tokenizer.cs), look for `_nestedTokensAdjustment`.

So it's safe to say I wanted to fix this problem, I tried to fix it, and I had to do a lot of tricky work that shouldn't have been necessary just to be compatible. Now if I could just remember specifics (like a convincing example) around my exact decision making process, but I can't.

I'm afraid I don't think much can be done about the quotes.

The paren issue could be the same issue, as in, my original implementation would have handled both cases as many people expect, but that doesn't mean we must fix both issues or neither, I'll comment further on that in #4543.

One last thing - in my opinion, this issue may be a minor annoyance, but sometimes a simple format string or other alternative not only gets around this issue, but is also easier to understand, and we should all prefer scripts that are easier to understand.

**Comment by briantist** [comment]
Thank you @lzybkr , I really appreciate the time you've taken to respond and the insight you've provided.

I agree on your last point especially. If it were not for the SO question I may have never run into the issue as I tend to refactor before that point, 

The only (somewhat?) valid scenario I can think of where this might come up without being a candidate for refactoring is in certain dynamic code generation scenarios. 

If you're replacing some tokens with sub-expressions you would expect to be able to do so consistently, generating code that would be considered messy if written by hand, but should run fine nonetheless.

Otherwise, that was my also my point in that most hand-written scripts would likely have used workaround that involve clearer code that is syntactically correct rather than invalid syntax that somehow works anyway.

**Comment by vors** [comment]
Not sure it's the exact same issue, but this works in bash on macos

```bash
python -c 'import os; print(os.listdir("."))'
```
```
bash-3.2$ python -c 'import os; print(os.listdir("."))'
['.DS_Store', 'foo', 'foo2']
```

And doesn't work in in powershell
```
  File "<string>", line 1
    import os; print(os.listdir(.))
                                ^
SyntaxError: invalid syntax
```

**Comment by mklement0** [comment]
@vors: 

It is not the same issue; your issue is related to how PowerShell rebuilds the command line behind the scenes for invoking external programs.

Unfortunately, however, that is much more of a real-world problem, as your example shows - I've summarized the current behavior and its problems at https://github.com/PowerShell/PowerShell-Docs/issues/2361 and an example of how problematic the current behavior is even on Windows can be found in [this SO answer](https://stackoverflow.com/a/51773694/45375).

**Comment by UberKluger** [comment]
I feel I must disagree with all the comments regarding maintaining the status quo to avoid breaking changes. As far I see it, if something is not working properly, it should be fixed. PowerShell has (or should have) a well defined grammar for expandable strings. In particular, the contents of an embedded subexpression should be an independent syntactic context. What goes on inside, stays inside, only the expression's value is relevant. When parsing the enclosing expandable string, the parser should neither see nor affect the enclosed sub-expression (as it processes the enclosing string), just interpolate the returned value (from a completely separate parse tree). Anything else just leads to confusion and unexpected, inexplicable failures (inexplicable by many users as evidenced by the issues raised).

The idea that fixing the apparent aberrant behaviour is somehow ***bad*** and should be avoided, lest those relying on it are inconvenienced, is misguided and not even historically consistent. Yes, there are many instances of apparent bugs being allowed to avoid the exterminator but there are also many instances where the end user just had to wear the problems they encountered due to a bug "fix". How many web pages were trashed whenever Microsoft&reg; fixed bugs or security holes in IE? How many programs died when a machine's DOS version was upgraded because they relied on undocumented INT 21 calls? Sure, you can argue that such programs shouldn't have relied on undocumented behaviour that could change or disappear with the next release but they worked at the time. And how about all the scripts which rely on the cmdlets which have been deleted from PS7 for "compatibility reasons"?

Arguments that it is best to avoid fixing something because it might cause some short term inconvenience are similar to saying that you don't want to get a cast for your broken arm because it's bulky and cumbersome so you'll just make do with a cloth sling. Sure, that kinda works but it's not likely to give the best overall outcome and the inconvenience would have only been temporary but the problems caused by avoiding it could be long term (and compound in unforeseen ways).

Any programming (or scripting) language should have a well defined grammar leading to predictable (and sensible) behaviour. Further, any construct which is grammatically correct should produce the expected result but one that is not correct should always be flagged as an error. I have read the comments regarding buckets and, to me, any implementation where a grammatically correct expression is flagged as an error while an incorrect one is evaluated (giving a grammatically unspecified result) should be placed in the "broken beyond all repair and must be replaced" bucket, despite the existence of a (probably small) number of end users utilising the incorrect behaviour (even if it is consistent and somewhat predictable after experimentation).

This is especially true when the fault can manifest due to very small changes in the input. In this issue (and #10413) simply changing the offending string from "" to " " (or anything other than "") results in expected behaviour. This means that end users could have a perfectly functioning script but simply changing a non-empty string in an embedded sub-expression into an empty one results in the script breaking. Thus, "" becomes a "special case" but only within an embedded subexpression (so only sometimes special). Special cases are something to be avoided, especially in the context of a language ***specification*** (the official documentation). As such, simply providing instructions for how to work around the "special case" is not a satisfactory long term solution. (More of a SO handy hint to solve an immediate issue.) 

As far as programs dying because they relied on undocumented "features", any scripts relying on the current "improper" behaviour are in the same boat. Using a workaround to get it operational despite the bug is fine but you shouldn't expect that the bug will never be fixed thereby necessitating an update to your script. At the very least, scripts (programs) that rely on unexpected (and also undocumented) behaviour should (and, in a perfect world, would) be written to notify the operator if they detect a change of environment (i.e. newer version of PS) since, as with INT 21, undocumented (or even documented) behaviour can change with a new release. Thus, at a minimum, this behaviour should be ***fully*** documented. Whether or not it is described as "deprecated" (i.e. planned to be changed) is a matter for discussion. I would say that it should. Something which should be straightforward but doesn't work as expected should not be just left as it is because there is a (potentially complicated) procedure which can be used to get the desired result.

Just as there are programs still running on XP that do not work on Win7 (let alone 10/11), support for old scripts which require out of date (or, frankly, just erroneous) behaviour must eventually end. Whether this is a "rip the band-aid off" change or a more gradual, hand-holding change, it should still happen. Some might suggest that having option selectable multiple behaviours for PS would provide some mitigation but this sort of thing can lead to an exponentially expanding multiverse of included behaviours probably ending up like the restaurant scene from Monty Python's Meaning of Life (warning, distressing scenes). Perhaps detecting the constructs affected by an impending change (12 months away perhaps) and then giving a (non-terminating) warning which included instructions to aid mitigation (only once per script invocation). Something like this perhaps
```
WARNING: The evaluation of expandable strings enclosing sub-expressions which contain character sequences that
resemble escaped double quotes (`" or "") will be changed in release X.YY. For information
regarding mitigation of the effects of this change, see https://...... To inhibit the display of this message, add
the value 123456 to the $SeenWarningsList preference variable array.
```
Yes, it is a bit of a mouthful but, again, the pain is temporary. As an aside, the idea of a list of individually inhibitable warnings of impending potentially breaking changes (or other useful info) leads to a cmdlet to list them so that the end user can keep up to date with things that might affect their scripts in the future (without searching for "planned changes to powershell").

Anyway, all reasoning and rationalisation aside,

(TLDR;) I think the issue boils down to this.

 `$('""')` and `"$('""')"` should evaluate to the same value but don't, this should be fixed.

**Comment by kevinholtkamp** [comment]
This might be old, but as you can see, it is still a problem. Hardcore backwards compatibility leads to problems all the times, and are rarely helpful (just look at windows).
If I really had a script relying on this "hack", I would simply not update powershell for this or install an old version side-by-side.

I can only agree with @UberKluger and say that `$('""')` really should equal `"$('""')"`.

**Comment by mubed** [comment]
Why is this issue closed, when it's still unsolved?
