### ISSUE TITLE
Grammar in CONTRIBUTING.md is very bad

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#3805]
fix grammar issues in .github/CONTRIBUTING.md

**Comment by mirichmo** [comment]
I fixed the title of the issue for you ;-)

**Comment by joeyaiello** [comment]
And yet both of you missed that "contributing" was spelled wrong. 😆

**Comment by iSazonov** [comment]
Can we close the Issue?

**Comment by SteveL-MSFT** [comment]
Any new issues please submit proposed changes as PRs.  Thanks!
