### ISSUE TITLE
Windows release build artifacts has packages from previous builds

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#4070]
- [x] When browsing the artifacts of the `v6.0.0-beta.3_.001` build, it shows packages from previous builds. The build definition should be updated to clean all directories before starting the build.

- [x] Please also make all maintainers admin of the release builds.

**Comment by TravisEz13** [comment]
Done

**Comment by MaximoTrinidad** [comment]
This goes all the way back to: https://github.com/PowerShell/PowerShell/issues/1850 

Sorry, didn't explained it better.  This is still happening in both Windows and Linux environments.
I have to manually remove the folders.

:)

**Comment by TravisEz13** [comment]
@MaximoTrinidad This issue is only for our release build environment.  I did not fix it anywhere else.  Although we use the build here it's wrapped in another build definition which I'm using to clean up the machine.

**Comment by TravisEz13** [comment]
@MaximoTrinidad  And our installer is a Side by Side installer, so it is currently by design that the installer does not remove the previous installation.
