### ISSUE TITLE
Auto-complete highlighting wrong items while toggling

### ISSUE THREAD

**Issue by aarontheadmin** [PowerShell/PowerShell#4388]
Steps to reproduce
------------------

```powershell
Get-Service a
```
In Windows, press Ctrl+Space to enumerate values and toggle to **atashost**.

Expected behavior
-----------------
![highlight_expected](https://user-images.githubusercontent.com/25207529/28741396-1488b234-73ca-11e7-9b12-882734286c01.PNG)

Actual behavior
---------------
In PowerShell-6.0.0-beta, each value is highlighted along path to toggle value of interest. This appears to happen for any PowerShell cmdlets or advanced functions.
![highlight_issue](https://user-images.githubusercontent.com/25207529/28741398-1f6e9416-73ca-11e7-9117-8e89f5b3a252.PNG)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@lzybkr do the changes you're working on for PSReadline address this?

**Comment by lzybkr** [comment]
Yes, it's fixed in this [branch](https://github.com/lzybkr/psreadline/tree/ansi_render)

**Comment by aarontheadmin** [comment]
The issue still exists in the current beta. Environment below and screenshot attached.
![ps6 capture](https://user-images.githubusercontent.com/25207529/32644006-c393981e-c593-11e7-9036-01f168a4cb60.PNG)


```
PS C:\Program Files\PowerShell\6.0.0-beta.9> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
The issue is fixed in PSReadLine 2.0 - but those changes have not been merged in this repo yet.

If you replace the PowerShell Core file `Microsoft.PowerShell.PSReadLine.dll` with the one from PSReadLine 2.0 (grab one from appveyor), you can verify it is fixed.

**Comment by aarontheadmin** [comment]
Thanks. I submitted another post but that can be ignored.
