### ISSUE TITLE
Task Scheduler Compatibility Problem

### ISSUE THREAD

**Issue by sundarchi1** [PowerShell/PowerShell#5919]
Just installed PowerShell 6.0. Was using 5.1 before.
I updated my scheduled tasks (in the Windows Server Task Scheduler) and I can't name the executable like before. The event gives a 0x80070002 (file not found) error when the task runs.

Checked Path variable, looks fine.
If I put in the full path to pwsh.exe, it works fine. But I'm concerned with doing that since it involves a 6.0.0 folder, which I assume will change.

Please update the installer to fix this shortcoming. (I used PowerShell-6.0.0-win-x64.msi)

![1](https://user-images.githubusercontent.com/31782486/35003884-3b5439f0-fabc-11e7-9656-3edc7d6bac83.png)
![2](https://user-images.githubusercontent.com/31782486/35003885-3b6bcb88-fabc-11e7-9e75-7a188b03e981.png)

**Comment by bergmeister** [comment]
I briefly looked into it and this is not related to the registry keys being HKCU in 6.0 (the same happens in HKLM).
All I can say is that the following works:
![image](https://user-images.githubusercontent.com/9250262/35013717-2979098c-fb06-11e7-8a2a-58812dbf2332.png)
Maybe a special registry key needs to be set for task scheduler?

**Comment by iSazonov** [comment]
You can use full path in Task Schedule `C:\Program Files\PowerShell\6.0.0\pwsh.exe`

**Comment by al-ign** [comment]
1) You should not use short names in Task Scheduler for obvious security reasons
2) Proper way to call any program by short name is adding it's location to PATH environment variable, or using 'App Paths' registry key.
To use PATH method, add executable location to global PATH, using sysdm.cpl
To use App Paths, create necessary subkey in 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths' key, for ex:
```
new-item 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths' -Name pwsh.exe -Value 'C:\Program Files\PowerShell\6.0.0\pwsh.exe' 
```
3) Concerning updating installer to support updating PATH and/or App Paths... well, it should.

**Comment by sundarchi1** [comment]
@iSazonov Bad idea, won't 6.0.0 change?

@al-ign Yes, installer should be fixed!

**Comment by iSazonov** [comment]
@sundarchi1 Feel free create new Issue for enhancing installer to update PATH.

**Comment by lwsrbrts** [comment]
I can see that my PATH variable ($env:Path) already contains the correct location for the pwsh.exe binary but I still get this issue, so adding it to the global PATH variable alone doesn't seem to be a suitable fix - at least not for me.

PowerShell.exe is located in the App Paths registry location though, so that is probably why that works.

![image](https://user-images.githubusercontent.com/15855642/35470991-317d77ce-034b-11e8-8c6e-abd24e0cc233.png)


![image](https://user-images.githubusercontent.com/15855642/35470971-a97ead48-034a-11e8-9492-328fb99bacef.png)

**Comment by iSazonov** [comment]
What is output `where.exe pwsh.exe`?

**Comment by lwsrbrts** [comment]
`C:\Program Files\PowerShell\6.0.1\pwsh.exe`

**Comment by MaximoTrinidad** [comment]
Keep in mind, due to the upcoming new release update(s) to PSCore, the version number will keep changing in the Program Files PowerShell path.  

So, whatever changes to the Environment Variable Path will become useless.

Now, we are at PSCore 6 version 6.0.1 and not 6.0.0.

Anything scheduled for PSCore6, the path will need to change manually. 
:)

**Comment by lwsrbrts** [comment]
@MaximoTrinidad - yes, that is basically the exact reason for this issue and my subsequent opening of #6046. The issue has opened wider discussion about what goes in the PATH and/or App Path when there's a side-by-side installation and in the event there is, if the user types in "pwsh.exe" from "cmd.exe", which version is opened?

**Comment by sundarchi1** [comment]
So what's the preferred fix here? Is the team going to make some changes?

**Comment by lwsrbrts** [comment]
@sundarchi1 @iSazonov wrote on #6046 that the App Path was actually already there but was using HKCU, instead of HKLM so registry changes were made to change App Path to be under HKLM in commit #5915 so I guess technically we're just waiting for the next release. The result of other discussions about possible SxS conflicts being that if someone is using SxS then they should really be using the zip and referencing that install manually, should they require it.

**Comment by sundarchi1** [comment]
Ok I'll check this out when the next version releases..

**Comment by sundarchi1** [comment]
What's the latest on this as of the v6.0.2 "releaes"? (someone spelled that wrong [here](https://github.com/PowerShell/PowerShell/releases)!)

**Comment by lwsrbrts** [comment]
I'm still seeing the problem in 6.0.2 but what is strange is that my system PATH (using cmd.exe) shows no mention at all of `C:\Program Files\PowerShell\6.0.2`. If I fire up `cmd.exe` and enter `pwsh.exe` I get: `'pwsh.exe' is not recognized as an internal or external command, operable program or batch file.`

If however I do `$env:path` inside PowerShell 6.0.2, the folder location is right there on the top line.

In Windows PowerShell 5.1, I get the system path.

I'm going to post this then I'll add `C:\Program Files\PowerShell\6.0.2` to the system PATH manually, reboot and see what happens.

![paths](https://user-images.githubusercontent.com/15855642/37539568-f576be58-294b-11e8-8177-7254799568d9.png)

**Comment by lwsrbrts** [comment]
Once added to the system PATH (and after a reboot) the scheduled task executes as expected.

**Comment by sundarchi1** [comment]
Will the next version add to PATH automatically?

**Comment by iSazonov** [comment]
We'll use standard  install path. Please feedback in https://github.com/PowerShell/PowerShell-RFC/pull/115

**Comment by sundarchi1** [comment]
Surprised to see this still unfixed in preview4 released today.
pwsh.exe still does not work in Task Scheduler without full path!
Note: I installed with "Add PowerShell to Path Environment Variable" checked, but it doesn't look like that actually did anything.

Please reopen.

**Comment by TravisEz13** [comment]
@sundarchi1 Did you follow the instructions here:  https://github.com/PowerShell/PowerShell/issues/5919#issuecomment-373817293

**Comment by lwsrbrts** [comment]
Not sure if the same fix for 6.1.0 p4 was applied to 6.0.3 but right after installation of 6.0.3 and before a reboot, the scheduled task didn't run. A reboot later and it worked as expected.

The system path was updated by the installer (leaving behind the previous entry referring to 6.0.2 however). I imagine that with 6.1 this will no longer be a problem if the installs all go in the same place?

**Comment by TravisEz13** [comment]
@sundarchi1  The previews don't add themselves to the path by design.  Only Stable builds do, we are considering adding `pwsh-preview` to the path as we did on Linux and Mac.

**Comment by sundarchi1** [comment]
@TravisEz13 Oh ok, so this should be fully resolved in 6.1 final.. will retest when that comes out.
Any hint when the final release comes out?

**Comment by bergmeister** [comment]
In the last community call, it was said that August will be the target for the final release.

**Comment by SteveL-MSFT** [comment]
@sundarchi1 https://github.com/PowerShell/PowerShell/pull/7345 should address your issue

**Comment by sundarchi1** [comment]
I have found success with the RC1 release.😃 Thanks to everyone involved.
pwsh-preview works in Task Scheduler, and I assume pwsh will work the same upon final release.
Note to anyone reading this later, rebooting after installing PowerShell is important, otherwise you will get 0x80070002 in Task Scheduler.
