### ISSUE TITLE
Powershell ISE crashes on Intellisense Ctrl+Space.

### ISSUE THREAD

**Issue by benliddicott** [PowerShell/PowerShell#6846]
Steps to reproduce
------------------
Use Windows Powershell ISE on Windows Build 17134

Enter the name of any cmdlet, a dash, then press ctrl+Space.

```powershell
Get-Help -[Ctrl+Space]
```

Expected behavior
-----------------

Should show intellisense popup.

Actual behavior
---------------
Instead of an intellisense dropdown, a small dot appears.

Messagebox as follows, followed by closing:
```
---------------------------
Windows PowerShell ISE - Error
---------------------------
An unexpected error has occurred, and Windows PowerShell ISE must close.
---------------------------
OK   
---------------------------
```
Running in the visual studio debugger shows two exceptions, one from Xaml (associated with the appearance of the dot) the other a NullReferenceException which appears to occur in the context of a timer.
If you break on the Xaml exception there is no nullreference exception presumably because of the loss of focus.

Environment data
----------------
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

```powershell
> $PSVersionTable

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17134.1                                                                                                                               
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17134.1                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

```
More information
---------------------

Running outside the debugger, instead of the intellisense pop-up I see a tiny dot appear, then the messagebox appears.

Running ISE in the visual studio debugger I see this:

```
Exception thrown: 'System.ArgumentException' in WindowsBase.dll
'Assertive' is not a valid value for property 'LiveSetting'.

Exception thrown: 'System.Xaml.XamlObjectWriterException' in System.Xaml.dll
Initialization of 'Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSetPresenter' threw an exception.
```

And:
```
Exception thrown: 'System.Xaml.XamlObjectWriterException' in System.Xaml.dll
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
Exception thrown: 'System.ArgumentException' in WindowsBase.dll
Exception thrown: 'System.Xaml.XamlObjectWriterException' in System.Xaml.dll
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
```

And:
```
Exception thrown: 'System.ComponentModel.InvalidAsynchronousStateException'
```

**Comment by markekraus** [comment]
Hi @benliddicott ! This repository is for PowerShell Core 6.0.0 and newer issues only. To file a bug report for Windows PowerShell or the PowerShell ISE, please use the UserVoice at https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by benliddicott** [comment]
How many different places do you have to log things? Feedback hub? GitHub? I didn't even know uservoice existed, and what's more it doesn't have a bug reporting form.

**Comment by markekraus** [comment]
Hi @benliddicott The UserVoice is called out in the issue template when you are creating a new issue in this repo. 

> For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
> - Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

Also, we welcome issues to be filed here and we will direct the user to where the issue needs to filed if it is not meant for this repo.

**Comment by SteveL-MSFT** [comment]
ISE crash has been fixed already and should be rolled out with next servicing update

**Comment by firooztnt** [comment]
@SteveL-MSFT Are you talking about KB4103721? Because I just installed it, rebooted my machine, and the ISE still crashes.

**Comment by SteveL-MSFT** [comment]
@firooztnt no, I just checked and it looks to be scheduled to be available last week of May.  Sorry, I have no control over when it goes out.

**Comment by ThangarasuS** [comment]
Please ping with microsoft update number once its been officially release, I do have the same issue.

**Comment by SteveL-MSFT** [comment]
I expect it to be in KB4100403.  The only workaround I'm aware of is to use VSCode.

**Comment by benliddicott** [comment]
@SteveL-MSFT Thanks for responding anyway! I've been using VSCode and to be fair it's a pretty good workaround. I may not go back...

**Comment by KiruthikaSubramaniam** [comment]
Please comment the solution for the above issue

**Comment by SteveL-MSFT** [comment]
The fix has already been released for some time now.  Solution is to update Win10.
