### ISSUE TITLE
Single Double-byte character display problem

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#7243]
I've tried all the new versions, and it's not displaying properly.
When I try to edit a command, using double-byte characters makes the characters appear mangled and overlapping.

**Comment by mklement0** [comment]
@he852100: Please provide an [MCVE (Minimal, Complete, and Verifiable Example)](http://stackoverflow.com/help/mcve), along with details about your environment (OS, PS version).

**Comment by cohato** [comment]
I can see same problem in Windows10 Redstone5 Insider Preview Build17713(JA-JP), 
Powershell version v10.0.17713.1000.

This problem does not occur in the Powershell_ISE(v10.0.17713.1000)

![powershell](https://user-images.githubusercontent.com/41607026/43118020-c973c98a-8f4a-11e8-9078-3e0fa8297d5b.jpg)

**Comment by he852100** [comment]
It's a stubborn problem, and you've never really solved it.
Change the window size, or remove the double-byte character normally. The fault recurs. It's universal。

**Comment by he852100** [comment]
When you enter a Chinese character, then delete it, or you want to insert other text before it, the fault occurs. Characters get messy
当输入一个中文字符，然后删除它，或者想在它之前插入其他文字，故障出现。字符变得混乱不堪，
In addition, when using a two-byte character variable, the variable reference fails
此外，当使用双字节字符变量时，变量引用会发生故障

**Comment by daxian-dbw** [comment]
@he852100 We need the repro steps and the environment data for the reported issue. I cannot reproduce this with `pwsh` 7.0.0-preview.4

![edit](https://user-images.githubusercontent.com/127450/66441683-cbaa4c80-e9ec-11e9-899e-7ad347c6eef7.gif)

For the environment data, run the following script and copy/paste the output here.
```powershell
& {
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $v = (Get-Module PSReadline).Version
    $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
    if ($m) {
        $v = "$v-" + $m.Matches[0].Groups[1].Value
    }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```

**Comment by iSazonov** [comment]
@he852100 Could you please add a comment why the issue closed? Fixed in 7.0.0-preview.4? Fixed in latest PSReadline?

**Comment by javierdlg** [comment]
Looks like this issue is still present for 2-byte and 4-byte characters in the latest windows 10 powershell. 
Visual Studio shipped an integrated terminal that also reproduces this issue in VS and in Powershell:
![image](https://user-images.githubusercontent.com/2334756/96023801-d2da1680-0e07-11eb-821c-ad105fccbd24.png)

**Comment by iSazonov** [comment]
@javierdlg Could you please check with latest PowerShell 7.1 RC and PSReadline 2.1.0 RC?
