### ISSUE TITLE
Blinking window while press TAB on Windows 10

### ISSUE THREAD

**Issue by liangzha** [PowerShell/PowerShell#7863]
Steps to reproduce
------------------
PowerShell 6.1.0 on Windows 10 (Build 17134)

Start a PowerShell session, press TAB w/o any other characters entered, the  client window of PowerShell 6.1.0 will be blinking for each press of TAB.

Expected behavior
-----------------
Nothing but as PowerShell 5.1

Actual behavior
---------------
The  client window of PowerShell 6.1.0 will be blinking for each press of TAB

Environment data
----------------

> $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@liangzha Please copy-paste $PSVersionTable value in the Issue description.

**Comment by liangzha** [comment]
Repost the result of $PSVersionTable:

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
I can not repo. Need more information.

**Comment by iSazonov** [comment]
@liangzha Thanks for your investigations! Currently PowerShell Core uses Utf-8 by default in console.

I can not repo the issue with "Consolas" font. You could try to check with/without PSReadline.

**Comment by liangzha** [comment]
@iSazonov thanks for the help. Now, I'm not sure if this issue is related my system code page (936, ANSI/OEM - Simplified Chinese GBK), while the default code page for PS 6 Core is UTF-8.
 
A screen capture of PowerShell console attached, within the .zip file.
[PowerShell 6 (x64) 9_27_2018 9_54_31 PM.zip](https://github.com/PowerShell/PowerShell/files/2424383/PowerShell.6.x64.9_27_2018.9_54_31.PM.zip)

Issue not be reproduced if PS6 Core started with option "-NonInteractive".

**Comment by SteveL-MSFT** [comment]
@liangzha Besides hitting `tab` do other operations cause the font to change?  If so, can you try `remove-module psreadline` and see if it still repros?

**Comment by liangzha** [comment]
Thank you for the help, guys! 

To be summarized:
1. PS Core 6.1.0 on Windows 10 (v17134), with system code page (936, ANSI/OEM - Simplified Chinese GBK);
2. PS Core 6.1.0 started with PSReadLine by default, code page UTF-8, Font size 16, with selected font type "Consolas", the console window blinks at each key down of TAB;
3. Issue could not be reproduced if with font "SimSun", neither with "Raster Fonts";
4. Issue could not be reproduced if remove module PSReadLine (via Remove-Module PSReadLine, the font of PS Core console will be defaulted to SimSun), and the blinking window comes back if press TAB after PSReadline added back (Import-Module PSReadLine, then the default font is Consolas).

**Comment by chuanjiao10** [comment]
1 yes , i confirm problem in ps 6.1 + Windows 10 17134 chinese version.

2 powershell.exe then **remove-module psreadline** ,i found i can not change font to 'consolas',
item consolas gone.

3 do not change font before enough test ！some chinese font  missing special characters，
eg：Mahjong  八万。
eg：♡

4
My font = 新宋体
My font size = 16

5 If you use a projector to display the command line,
Font = 黑体
Font size = 28

6 In windows, in general, it is not recommended to change the font. 
In the terminal software to ssh to to linux, we have more custom fonts. I use 雅黑mono.

**Comment by SunCosmo** [comment]
1) Similar problem with font type "Consolas" "Courier New" "Lucida Console" "Lucida Sans" and "Typewriter";
2) The blinks show up under all the font sizes;
3) These two TrueType fonts: "MS Gothic" "SimSun-ExB" are OK;

```
PS C:\Users\sunzcosmo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is fixed via https://github.com/lzybkr/PSReadLine/pull/771

**Comment by daisen** [comment]
the problem is still there.

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
