### ISSUE TITLE
The font changes from 'Consolas' to '新宋体' when execute commands as Administrator

### ISSUE THREAD

**Issue by amapleaf** [PowerShell/PowerShell#9532]
# Steps to reproduce

1. Right-click on desktop
2. Select `PowerShell 6`->`Open here as Administrator`
3. Type `pip install flask` in the opened window (actually, every command)

![image](https://user-images.githubusercontent.com/29867903/57174538-1f7b9d00-6e73-11e9-8965-33001be741c1.png)

# Expected behavior

It can execute commands normally.

# Actual behavior

The result of command is right. But during execution, the font changes from `Consolas` from `新宋体` and changes back after the execution end.

![image](https://user-images.githubusercontent.com/29867903/57174635-6fa72f00-6e74-11e9-881a-27a45f55aeb1.png)

![image](https://user-images.githubusercontent.com/29867903/57174640-88174980-6e74-11e9-9d53-37bc37a93d4d.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is an issue with PSReadLine which should be fixed in beta4 which should be published next week.

**Comment by pboymt** [comment]
> This is an issue with PSReadLine which should be fixed in beta4 which should be published next week.

This bug still exists in PowerShell 6.2.1 on Windows 10 1903.

**Comment by SteveL-MSFT** [comment]
@pboymt 6.2.1 still ships with PSReadLine 2.0.0-beta3.  Can you install beta4 from PSGallery and see if it is still an issue?

**Comment by daxian-dbw** [comment]
Also a duplicate of https://github.com/PowerShell/PSReadLine/issues/964
